// 마지막 남은 뼈대 (특수각 삼각비 · 부분집합 · 주사위 확률 · 소수 색칠)
module.exports = {

"f339376b": { en:"0.%1$s is the same as %2$s/10.\nColour %3$s of the 10 parts.", ja:"0.%1$s は %2$s/10 と同じです。\n10 こ のうち %3$s こを ぬれば いいです。", zh:"0.%1$s 和 %2$s/10 相同。\n把10格中的 %3$s 格涂上即可。", es:"0,%1$s es lo mismo que %2$s/10.\nColorea %3$s de las 10 partes.", fr:"0,%1$s équivaut à %2$s/10.\nColorie %3$s des 10 parts.", de:"0,%1$s ist dasselbe wie %2$s/10.\nMale %3$s der 10 Teile aus.", pt:"0,%1$s é o mesmo que %2$s/10.\nPinte %3$s das 10 partes.", ru:"0,%1$s — это то же самое, что %2$s/10.\nЗакрась %3$s из 10 частей.", vi:"0,%1$s bằng %2$s/10.\nHãy tô %3$s trong 10 phần.", th:"0.%1$s เท่ากับ %2$s/10\nระบายสี %3$s ช่องจาก 10 ช่อง", in:"0,%1$s sama dengan %2$s/10.\nWarnai %3$s dari 10 bagian." },
"d6fcc9c2": { en:"What is the value of %1$s %2$s°? (write fractions like 1/2)", ja:"%1$s %2$s° の値は? (分数は 1/2 のように)", zh:"%1$s %2$s° 的值是? (分数写成 1/2 这样)", es:"¿Cuánto vale %1$s %2$s°? (escribe las fracciones como 1/2)", fr:"Que vaut %1$s %2$s° ? (écris les fractions comme 1/2)", de:"Wie groß ist %1$s %2$s°? (Brüche wie 1/2 schreiben)", pt:"Quanto vale %1$s %2$s°? (escreva frações como 1/2)", ru:"Чему равен %1$s %2$s°? (дроби записывай как 1/2)", vi:"%1$s %2$s° bằng bao nhiêu? (viết phân số dạng 1/2)", th:"%1$s %2$s° มีค่าเท่าใด? (เขียนเศษส่วนแบบ 1/2)", in:"Berapa nilai %1$s %2$s°? (tulis pecahan seperti 1/2)" },
"2d7284ee": { en:"This is a special-angle ratio. %1$s%2$s° = %3$s\nIt helps to memorise the values for 30°, 45° and 60°.", ja:"特殊角の三角比です。%1$s%2$s° = %3$s\n30°・45°・60° の値は覚えておくと便利です。", zh:"这是特殊角的三角比。%1$s%2$s° = %3$s\n记住30°、45°、60°的值会很方便。", es:"Es una razón trigonométrica de ángulo notable. %1$s%2$s° = %3$s\nConviene memorizar los valores de 30°, 45° y 60°.", fr:"C'est un rapport trigonométrique d'angle remarquable. %1$s%2$s° = %3$s\nIl est utile de retenir les valeurs de 30°, 45° et 60°.", de:"Das ist ein Wert für einen besonderen Winkel. %1$s%2$s° = %3$s\nDie Werte für 30°, 45° und 60° merkt man sich am besten.", pt:"É uma razão trigonométrica de ângulo notável. %1$s%2$s° = %3$s\nVale a pena decorar os valores de 30°, 45° e 60°.", ru:"Это тригонометрическое отношение для особого угла. %1$s%2$s° = %3$s\nЗначения для 30°, 45° и 60° стоит запомнить.", vi:"Đây là tỉ số lượng giác của góc đặc biệt. %1$s%2$s° = %3$s\nNên thuộc các giá trị của 30°, 45° và 60°.", th:"นี่คืออัตราส่วนตรีโกณมิติของมุมพิเศษ %1$s%2$s° = %3$s\nควรจำค่าของ 30°, 45° และ 60° ไว้", in:"Ini perbandingan trigonometri sudut istimewa. %1$s%2$s° = %3$s\nSebaiknya hafalkan nilai 30°, 45°, dan 60°." },
"f046f32a": { en:"How many subsets does a set with %1$s elements have?", ja:"要素が %1$s 個の集合の部分集合の個数は?", zh:"含有 %1$s 个元素的集合有多少个子集?", es:"¿Cuántos subconjuntos tiene un conjunto de %1$s elementos?", fr:"Combien de sous-ensembles a un ensemble de %1$s éléments ?", de:"Wie viele Teilmengen hat eine Menge mit %1$s Elementen?", pt:"Quantos subconjuntos tem um conjunto de %1$s elementos?", ru:"Сколько подмножеств у множества из %1$s элементов?", vi:"Tập hợp có %1$s phần tử có bao nhiêu tập con?", th:"เซตที่มีสมาชิก %1$s ตัว มีสับเซตกี่เซต?", in:"Berapa banyak himpunan bagian dari himpunan dengan %1$s anggota?" },
"710ba473": { en:"Number of subsets = 2ⁿ = 2^%1$s = %2$s.\n(There are %3$s proper subsets.)", ja:"部分集合の個数 = 2ⁿ = 2^%1$s = %2$s 個です。\n(真部分集合は %3$s 個)", zh:"子集个数 = 2ⁿ = 2^%1$s = %2$s 个。\n(真子集有 %3$s 个)", es:"Número de subconjuntos = 2ⁿ = 2^%1$s = %2$s.\n(Hay %3$s subconjuntos propios.)", fr:"Nombre de sous-ensembles = 2ⁿ = 2^%1$s = %2$s.\n(Il y a %3$s sous-ensembles propres.)", de:"Anzahl der Teilmengen = 2ⁿ = 2^%1$s = %2$s.\n(Es gibt %3$s echte Teilmengen.)", pt:"Número de subconjuntos = 2ⁿ = 2^%1$s = %2$s.\n(Há %3$s subconjuntos próprios.)", ru:"Число подмножеств = 2ⁿ = 2^%1$s = %2$s.\n(Собственных подмножеств %3$s.)", vi:"Số tập con = 2ⁿ = 2^%1$s = %2$s.\n(Có %3$s tập con thực sự.)", th:"จำนวนสับเซต = 2ⁿ = 2^%1$s = %2$s เซต\n(สับเซตแท้มี %3$s เซต)", in:"Banyak himpunan bagian = 2ⁿ = 2^%1$s = %2$s.\n(Ada %3$s himpunan bagian sejati.)" },
"fb01043c": { en:"What is the probability of rolling %1$s or less on one throw of a die? (numerator in lowest terms)", ja:"さいころを1回投げて %1$s 以下の目が出る確率は? (既約分数の分子)", zh:"掷一次骰子，点数不超过 %1$s 的概率是? (最简分数的分子)", es:"¿Cuál es la probabilidad de sacar %1$s o menos al lanzar un dado? (numerador de la fracción irreducible)", fr:"Quelle est la probabilité d'obtenir %1$s ou moins en lançant un dé ? (numérateur de la fraction irréductible)", de:"Wie groß ist die Wahrscheinlichkeit, mit einem Würfel höchstens %1$s zu werfen? (Zähler des gekürzten Bruchs)", pt:"Qual é a probabilidade de tirar %1$s ou menos num lançamento de dado? (numerador da fração irredutível)", ru:"Какова вероятность выпадения не более %1$s при одном броске кубика? (числитель несократимой дроби)", vi:"Xác suất gieo một con xúc xắc được số không quá %1$s là bao nhiêu? (tử số của phân số tối giản)", th:"ความน่าจะเป็นที่ทอยลูกเต๋าหนึ่งครั้งแล้วได้แต้มไม่เกิน %1$s คือ? (ตัวเศษของเศษส่วนอย่างต่ำ)", in:"Berapa peluang muncul mata dadu paling banyak %1$s pada satu lemparan? (pembilang pecahan paling sederhana)" },
"4fcaf9c5": { en:"There are %2$s outcomes of %1$s or less, out of 6 in total. %3$s/6 = %4$s/%5$s", ja:"%1$s 以下は %2$s とおり、全体は 6 とおりです。%3$s/6 = %4$s/%5$s", zh:"不超过 %1$s 的有 %2$s 种，总共有6种。%3$s/6 = %4$s/%5$s", es:"Hay %2$s casos de %1$s o menos, de 6 en total. %3$s/6 = %4$s/%5$s", fr:"Il y a %2$s cas de %1$s ou moins, sur 6 au total. %3$s/6 = %4$s/%5$s", de:"Es gibt %2$s Fälle mit höchstens %1$s, von insgesamt 6. %3$s/6 = %4$s/%5$s", pt:"Há %2$s casos de %1$s ou menos, de 6 no total. %3$s/6 = %4$s/%5$s", ru:"Исходов не более %1$s — %2$s из 6 возможных. %3$s/6 = %4$s/%5$s", vi:"Có %2$s kết quả không quá %1$s, trong tổng số 6. %3$s/6 = %4$s/%5$s", th:"มี %2$s แบบที่ไม่เกิน %1$s จากทั้งหมด 6 แบบ %3$s/6 = %4$s/%5$s", in:"Ada %2$s hasil dengan nilai paling banyak %1$s dari total 6. %3$s/6 = %4$s/%5$s" },

};
