// 도형 분류 안내 · 각의 종류
module.exports = {

"74cc085d": { en:"%1$s\nEven if the colours differ, the same shape goes in the same basket.", ja:"%1$s\n色が ちがっても かたちが 同じなら 同じ かごです。", zh:"%1$s\n颜色不同也没关系，形状相同就放同一个篮子。", es:"%1$s\nAunque el color cambie, la misma forma va en la misma cesta.", fr:"%1$s\nMême si la couleur change, la même forme va dans le même panier.", de:"%1$s\nAuch bei anderer Farbe gehört dieselbe Form in denselben Korb.", pt:"%1$s\nMesmo com cores diferentes, a mesma forma vai na mesma cesta.", ru:"%1$s\nДаже если цвет другой, одинаковые фигуры кладём в одну корзину.", vi:"%1$s\nDù khác màu, hình giống nhau thì vào cùng một giỏ.", th:"%1$s\nแม้สีต่างกัน ถ้ารูปทรงเหมือนกันก็ใส่ตะกร้าเดียวกัน", in:"%1$s\nMeski warnanya berbeda, bentuk yang sama masuk ke keranjang yang sama." },
"28a6838e": { en:"%1$s° is %2$s.", ja:"%1$s° は %2$s です。", zh:"%1$s° 是%2$s。", es:"%1$s° es un %2$s.", fr:"%1$s° est un %2$s.", de:"%1$s° ist ein %2$s.", pt:"%1$s° é um %2$s.", ru:"%1$s° — это %2$s.", vi:"%1$s° là %2$s.", th:"%1$s° คือ%2$s", in:"%1$s° adalah %2$s." },
"394c5f1b": { en:"%1$s° is %2$s.\nThat is %3$s° narrower than a right angle (90°).", ja:"%1$s° は %2$s です。\n直角(90°)より %3$s° せまいです。", zh:"%1$s° 是%2$s。\n比直角(90°)小 %3$s°。", es:"%1$s° es un %2$s.\nEs %3$s° menos que un ángulo recto (90°).", fr:"%1$s° est un %2$s.\nC'est %3$s° de moins qu'un angle droit (90°).", de:"%1$s° ist ein %2$s.\nDas sind %3$s° weniger als ein rechter Winkel (90°).", pt:"%1$s° é um %2$s.\nÉ %3$s° menor que um ângulo reto (90°).", ru:"%1$s° — это %2$s.\nЭто на %3$s° меньше прямого угла (90°).", vi:"%1$s° là %2$s.\nNhỏ hơn góc vuông (90°) %3$s°.", th:"%1$s° คือ%2$s\nแคบกว่ามุมฉาก (90°) อยู่ %3$s°", in:"%1$s° adalah %2$s.\nItu %3$s° lebih kecil dari sudut siku-siku (90°)." },
"9e6c9d79": { en:"%1$s° is %2$s.\nThat is %3$s° wider than a right angle (90°).", ja:"%1$s° は %2$s です。\n直角(90°)より %3$s° ひろいです。", zh:"%1$s° 是%2$s。\n比直角(90°)大 %3$s°。", es:"%1$s° es un %2$s.\nEs %3$s° más que un ángulo recto (90°).", fr:"%1$s° est un %2$s.\nC'est %3$s° de plus qu'un angle droit (90°).", de:"%1$s° ist ein %2$s.\nDas sind %3$s° mehr als ein rechter Winkel (90°).", pt:"%1$s° é um %2$s.\nÉ %3$s° maior que um ângulo reto (90°).", ru:"%1$s° — это %2$s.\nЭто на %3$s° больше прямого угла (90°).", vi:"%1$s° là %2$s.\nLớn hơn góc vuông (90°) %3$s°.", th:"%1$s° คือ%2$s\nกว้างกว่ามุมฉาก (90°) อยู่ %3$s°", in:"%1$s° adalah %2$s.\nItu %3$s° lebih besar dari sudut siku-siku (90°)." },
"b0aed67a": { en:"%1$s° is %2$s.\nIt stands perfectly upright.", ja:"%1$s° は %2$s です。\nまっすぐ 立った 角です。", zh:"%1$s° 是%2$s。\n是端端正正立着的角。", es:"%1$s° es un %2$s.\nEs un ángulo perfectamente recto.", fr:"%1$s° est un %2$s.\nC'est un angle parfaitement droit.", de:"%1$s° ist ein %2$s.\nEr steht genau senkrecht.", pt:"%1$s° é um %2$s.\nÉ um ângulo perfeitamente em pé.", ru:"%1$s° — это %2$s.\nОн стоит совершенно прямо.", vi:"%1$s° là %2$s.\nĐó là góc dựng thẳng đứng.", th:"%1$s° คือ%2$s\nเป็นมุมที่ตั้งตรงพอดี", in:"%1$s° adalah %2$s.\nSudutnya berdiri tegak sempurna." },

};
