// 마지막 조립식 해설 — 규칙 찾기 · 모양 고르기 · 시계 읽기 · 수직선
module.exports = {

"54ac9abe": { en:"The rule is %1$s and %2$s taking turns. After %3$s comes %4$s.", ja:"%1$s と %2$s が こうごに でてくる きまりです。%3$s の つぎは %4$s です。", zh:"规律是 %1$s 和 %2$s 交替出现。%3$s 后面是 %4$s。", es:"La regla es %1$s y %2$s alternándose. Después de %3$s viene %4$s.", fr:"La règle : %1$s et %2$s alternent. Après %3$s vient %4$s.", de:"Die Regel: %1$s und %2$s wechseln sich ab. Nach %3$s kommt %4$s.", pt:"A regra é %1$s e %2$s se alternando. Depois de %3$s vem %4$s.", ru:"Правило: %1$s и %2$s чередуются. После %3$s идёт %4$s.", vi:"Quy luật là %1$s và %2$s xen kẽ nhau. Sau %3$s là %4$s.", th:"กฎคือ %1$s กับ %2$s สลับกัน หลัง %3$s คือ %4$s", in:"Aturannya %1$s dan %2$s bergantian. Setelah %3$s adalah %4$s." },
"5c76e40f": { en:"That is the %1$s. It is number %2$s.", ja:"%1$s の かたちです。%2$s ばんです。", zh:"那是%1$s。是第 %2$s 个。", es:"Ese es el %1$s. Es el número %2$s.", fr:"C'est le %1$s. C'est le numéro %2$s.", de:"Das ist das %1$s. Es ist Nummer %2$s.", pt:"Esse é o %1$s. É o número %2$s.", ru:"Это %1$s. Он под номером %2$s.", vi:"Đó là %1$s. Là số %2$s.", th:"นั่นคือ%1$s อยู่ลำดับที่ %2$s", in:"Itu %1$s. Nomor %2$s." },
"1c847ed5": { en:"The short hand points at %1$s and the long hand at 12, so it is %2$s o'clock.", ja:"短いはりが %1$s、長いはりが 12 を さしているので %2$s 時です。", zh:"短针指着 %1$s，长针指着12，所以是 %2$s 点。", es:"La manecilla corta apunta a %1$s y la larga a 12, así que son las %2$s en punto.", fr:"La petite aiguille est sur %1$s et la grande sur 12 : il est %2$s heures pile.", de:"Der kleine Zeiger steht auf %1$s, der große auf 12 — also %2$s Uhr.", pt:"O ponteiro pequeno aponta para %1$s e o grande para 12, então são %2$s horas em ponto.", ru:"Короткая стрелка на %1$s, длинная на 12 — значит ровно %2$s часов.", vi:"Kim ngắn chỉ %1$s, kim dài chỉ 12, nên là %2$s giờ đúng.", th:"เข็มสั้นชี้ที่ %1$s เข็มยาวชี้ที่ 12 จึงเป็นเวลา %2$s นาฬิกาตรง", in:"Jarum pendek menunjuk %1$s dan jarum panjang menunjuk 12, jadi pukul %2$s tepat." },
"ed836a0a": { en:"The short hand is between %1$s and %2$s and the long hand points at 6, so it is %3$s:30.", ja:"短いはりが %1$s と %2$s の あいだ、長いはりが 6 を さしているので %3$s 時 30 分です。", zh:"短针在 %1$s 和 %2$s 之间，长针指着6，所以是 %3$s 点30分。", es:"La manecilla corta está entre %1$s y %2$s y la larga apunta al 6, así que son las %3$s:30.", fr:"La petite aiguille est entre %1$s et %2$s et la grande sur 6 : il est %3$s h 30.", de:"Der kleine Zeiger steht zwischen %1$s und %2$s, der große auf 6 — also %3$s:30 Uhr.", pt:"O ponteiro pequeno está entre %1$s e %2$s e o grande aponta para 6, então são %3$s:30.", ru:"Короткая стрелка между %1$s и %2$s, длинная на 6 — значит %3$s:30.", vi:"Kim ngắn nằm giữa %1$s và %2$s, kim dài chỉ 6, nên là %3$s giờ 30 phút.", th:"เข็มสั้นอยู่ระหว่าง %1$s กับ %2$s และเข็มยาวชี้ที่ 6 จึงเป็นเวลา %3$s:30", in:"Jarum pendek di antara %1$s dan %2$s, jarum panjang menunjuk 6, jadi pukul %3$s:30." },
"cc9224e2": { en:"It is %1$s steps to the right of 0.\n%2$s is less than 10.", ja:"0 から 右へ %1$s めもり すすんだ ところです。\n%2$s は 10 より 小さいです。", zh:"是从0向右走 %1$s 格的位置。\n%2$s 比10小。", es:"Está %1$s pasos a la derecha del 0.\n%2$s es menor que 10.", fr:"C'est à %1$s pas à droite de 0.\n%2$s est plus petit que 10.", de:"Das sind %1$s Schritte rechts von 0.\n%2$s ist kleiner als 10.", pt:"Fica %1$s passos à direita do 0.\n%2$s é menor que 10.", ru:"Это %1$s шагов вправо от 0.\n%2$s меньше 10.", vi:"Đó là %1$s bước sang phải kể từ 0.\n%2$s nhỏ hơn 10.", th:"อยู่ห่างจาก 0 ไปทางขวา %1$s ช่อง\n%2$s น้อยกว่า 10", in:"Letaknya %1$s langkah ke kanan dari 0.\n%2$s lebih kecil dari 10." },
"298087b1": { en:"It is %1$s steps to the right of 0.\n%2$s is greater than 10.", ja:"0 から 右へ %1$s めもり すすんだ ところです。\n%2$s は 10 より 大きいです。", zh:"是从0向右走 %1$s 格的位置。\n%2$s 比10大。", es:"Está %1$s pasos a la derecha del 0.\n%2$s es mayor que 10.", fr:"C'est à %1$s pas à droite de 0.\n%2$s est plus grand que 10.", de:"Das sind %1$s Schritte rechts von 0.\n%2$s ist größer als 10.", pt:"Fica %1$s passos à direita do 0.\n%2$s é maior que 10.", ru:"Это %1$s шагов вправо от 0.\n%2$s больше 10.", vi:"Đó là %1$s bước sang phải kể từ 0.\n%2$s lớn hơn 10.", th:"อยู่ห่างจาก 0 ไปทางขวา %1$s ช่อง\n%2$s มากกว่า 10", in:"Letaknya %1$s langkah ke kanan dari 0.\n%2$s lebih besar dari 10." },
"c9b3271e": { en:"It is %1$s steps to the right of 0.\n%2$s is exactly 10.", ja:"0 から 右へ %1$s めもり すすんだ ところです。\n%2$s は ちょうど 10 です。", zh:"是从0向右走 %1$s 格的位置。\n%2$s 正好是10。", es:"Está %1$s pasos a la derecha del 0.\n%2$s es exactamente 10.", fr:"C'est à %1$s pas à droite de 0.\n%2$s vaut exactement 10.", de:"Das sind %1$s Schritte rechts von 0.\n%2$s ist genau 10.", pt:"Fica %1$s passos à direita do 0.\n%2$s é exatamente 10.", ru:"Это %1$s шагов вправо от 0.\n%2$s — это ровно 10.", vi:"Đó là %1$s bước sang phải kể từ 0.\n%2$s đúng bằng 10.", th:"อยู่ห่างจาก 0 ไปทางขวา %1$s ช่อง\n%2$s เท่ากับ 10 พอดี", in:"Letaknya %1$s langkah ke kanan dari 0.\n%2$s tepat 10." },

};
