/**
 * 문제 화면(LessonActivity) 문자열 — 조작 안내 · 오답 안내 · 칭찬 · 결과.
 *
 * strings.js 가 이 파일을 합쳐서 쓴다. 화면별로 나눠 둬야 한 파일이 안 비대해진다.
 * 번체 중국어(zh-rTW·zh-rHK)는 zh 에서 자동 변환되므로 여기 안 쓴다.
 */
module.exports = {

// ---------- 조작 안내 ----------
play_count_tap: { ko:"👆 그림을 하나씩 짚어 세어 보세요", en:"👆 Tap each picture to count them", ja:"👆 えを ひとつずつ さわって かぞえよう", zh:"👆 逐个点击图片来数一数", es:"👆 Toca cada dibujo para contarlos", fr:"👆 Touche chaque image pour compter", de:"👆 Tippe jedes Bild an und zähle mit", pt:"👆 Toque em cada figura para contar", ru:"👆 Нажимай на картинки и считай", vi:"👆 Chạm từng hình để đếm", th:"👆 แตะรูปทีละรูปเพื่อนับ", in:"👆 Ketuk tiap gambar untuk menghitung" },
play_count_move: { ko:"👆 톡 누르면 세어지고, 끌면 옮겨져요", en:"👆 Tap to count, drag to move", ja:"👆 タップで かぞえて、ドラッグで うごかせるよ", zh:"👆 点一下就数，拖动就能移动", es:"👆 Toca para contar, arrastra para mover", fr:"👆 Touche pour compter, glisse pour déplacer", de:"👆 Tippen zum Zählen, Ziehen zum Bewegen", pt:"👆 Toque para contar, arraste para mover", ru:"👆 Нажми, чтобы посчитать; потяни, чтобы передвинуть", vi:"👆 Chạm để đếm, kéo để di chuyển", th:"👆 แตะเพื่อนับ ลากเพื่อย้าย", in:"👆 Ketuk untuk menghitung, seret untuk memindahkan" },
play_count_now: { ko:"👆 지금까지 %1$d 개 세었어요", en:"👆 Counted %1$d so far", ja:"👆 いままで %1$d こ かぞえたよ", zh:"👆 到目前为止数了 %1$d 个", es:"👆 Llevas %1$d contados", fr:"👆 %1$d comptés jusqu'ici", de:"👆 Bisher %1$d gezählt", pt:"👆 %1$d contados até agora", ru:"👆 Посчитано: %1$d", th:"👆 นับได้ %1$d แล้ว", vi:"👆 Đã đếm được %1$d", in:"👆 Sudah dihitung %1$d" },
play_reset_count: { ko:"다시 세기", en:"Count again", ja:"もういちど かぞえる", zh:"重新数", es:"Contar de nuevo", fr:"Recompter", de:"Neu zählen", pt:"Contar de novo", ru:"Посчитать заново", vi:"Đếm lại", th:"นับใหม่", in:"Hitung lagi" },
play_reset_move: { ko:"처음으로", en:"Start over", ja:"さいしょから", zh:"从头开始", es:"Empezar de nuevo", fr:"Recommencer", de:"Von vorn", pt:"Recomeçar", ru:"Сначала", vi:"Làm lại", th:"เริ่มใหม่", in:"Mulai lagi" },
play_reset_put: { ko:"다시 담기", en:"Put back", ja:"入れなおす", zh:"重新放", es:"Volver a poner", fr:"Remettre", de:"Neu einlegen", pt:"Colocar de novo", ru:"Разложить заново", vi:"Xếp lại", th:"ใส่ใหม่", in:"Masukkan lagi" },
play_reset_bar: { ko:"다시 세우기", en:"Rebuild", ja:"作りなおす", zh:"重新建立", es:"Reconstruir", fr:"Refaire", de:"Neu bauen", pt:"Refazer", ru:"Построить заново", vi:"Dựng lại", th:"สร้างใหม่", in:"Bangun ulang" },
play_reset_gather: { ko:"다시 옮기기", en:"Move again", ja:"もういちど うつす", zh:"重新搬", es:"Mover de nuevo", fr:"Redéplacer", de:"Neu umsetzen", pt:"Mover de novo", ru:"Перенести заново", vi:"Chuyển lại", th:"ย้ายใหม่", in:"Pindahkan lagi" },

play_clock: { ko:"🕐 바늘을 끌어서 시각을 맞춰 보세요", en:"🕐 Drag the hands to set the time", ja:"🕐 はりを ドラッグして 時間を あわせよう", zh:"🕐 拖动指针来对准时间", es:"🕐 Arrastra las manecillas para poner la hora", fr:"🕐 Fais glisser les aiguilles pour régler l'heure", de:"🕐 Zieh die Zeiger auf die richtige Zeit", pt:"🕐 Arraste os ponteiros para acertar a hora", ru:"🕐 Потяни стрелки, чтобы выставить время", vi:"🕐 Kéo kim để chỉnh giờ", th:"🕐 ลากเข็มเพื่อตั้งเวลา", in:"🕐 Seret jarum untuk mengatur waktu" },
play_clock_now: { ko:"🕐 지금 맞춘 시각: %1$d시 %2$d분", en:"🕐 Now showing %1$d:%2$02d", ja:"🕐 いまの 時こく: %1$d時 %2$d分", zh:"🕐 现在是 %1$d 点 %2$d 分", es:"🕐 Ahora marca %1$d:%2$02d", fr:"🕐 Il est %1$d h %2$02d", de:"🕐 Jetzt %1$d:%2$02d Uhr", pt:"🕐 Agora marca %1$d:%2$02d", ru:"🕐 Сейчас %1$d:%2$02d", vi:"🕐 Hiện là %1$d giờ %2$d phút", th:"🕐 ตอนนี้ %1$d:%2$02d", in:"🕐 Sekarang %1$d:%2$02d" },
play_group: { ko:"🧺 %1$s 를 끌어서 %2$d개의 바구니에 똑같이 나눠 담아요", en:"🧺 Drag the %1$s to share them equally into %2$d baskets", ja:"🧺 %1$s を ドラッグして %2$d この かごに 同じように わけよう", zh:"🧺 拖动 %1$s，平均分到 %2$d 个篮子里", es:"🧺 Arrastra los %1$s y repártelos en %2$d cestas", fr:"🧺 Fais glisser les %1$s pour les répartir dans %2$d paniers", de:"🧺 Zieh die %1$s gleichmäßig in %2$d Körbe", pt:"🧺 Arraste os %1$s e divida em %2$d cestas", ru:"🧺 Перетащи %1$s поровну в %2$d корзины", vi:"🧺 Kéo %1$s chia đều vào %2$d giỏ", th:"🧺 ลาก %1$s แบ่งใส่ตะกร้า %2$d ใบเท่า ๆ กัน", in:"🧺 Seret %1$s dan bagi rata ke %2$d keranjang" },
play_paint: { ko:"🍰 조각을 눌러서 색칠해 보세요", en:"🍰 Tap the pieces to colour them", ja:"🍰 ピースを おして ぬってみよう", zh:"🍰 点击小块来涂色", es:"🍰 Toca las piezas para colorearlas", fr:"🍰 Touche les parts pour les colorier", de:"🍰 Tippe die Teile an und färbe sie", pt:"🍰 Toque nas partes para pintar", ru:"🍰 Нажимай на кусочки, чтобы закрасить", vi:"🍰 Chạm vào các mảnh để tô màu", th:"🍰 แตะชิ้นส่วนเพื่อระบายสี", in:"🍰 Ketuk potongannya untuk mewarnai" },
play_paint_now: { ko:"🍰 지금 %1$d / %2$d 칸을 칠했어요", en:"🍰 Coloured %1$d of %2$d", ja:"🍰 いま %1$d / %2$d ぬったよ", zh:"🍰 已涂 %1$d / %2$d 格", es:"🍰 Coloreadas %1$d de %2$d", fr:"🍰 %1$d sur %2$d coloriées", de:"🍰 %1$d von %2$d gefärbt", pt:"🍰 Pintadas %1$d de %2$d", ru:"🍰 Закрашено %1$d из %2$d", vi:"🍰 Đã tô %1$d / %2$d", th:"🍰 ระบายแล้ว %1$d / %2$d", in:"🍰 Diwarnai %1$d dari %2$d" },
play_sort: { ko:"🔺 도형을 알맞은 바구니로 끌어 담아요", en:"🔺 Drag each shape into the right basket", ja:"🔺 かたちを ただしい かごへ ドラッグしよう", zh:"🔺 把图形拖到对应的篮子里", es:"🔺 Arrastra cada figura a su cesta", fr:"🔺 Fais glisser chaque forme dans le bon panier", de:"🔺 Zieh jede Form in den richtigen Korb", pt:"🔺 Arraste cada figura para a cesta certa", ru:"🔺 Перетащи фигуры в нужные корзины", vi:"🔺 Kéo mỗi hình vào đúng giỏ", th:"🔺 ลากรูปทรงไปใส่ตะกร้าที่ถูกต้อง", in:"🔺 Seret tiap bangun ke keranjang yang tepat" },
play_sort_left: { ko:"🔺 아직 %1$d개 남았어요", en:"🔺 %1$d still to go", ja:"🔺 あと %1$d こ", zh:"🔺 还剩 %1$d 个", es:"🔺 Faltan %1$d", fr:"🔺 Encore %1$d", de:"🔺 Noch %1$d übrig", pt:"🔺 Faltam %1$d", ru:"🔺 Осталось %1$d", vi:"🔺 Còn %1$d", th:"🔺 เหลืออีก %1$d", in:"🔺 Sisa %1$d lagi" },
play_sort_done: { ko:"🔺 다 담았어요!", en:"🔺 All sorted!", ja:"🔺 ぜんぶ 入れたよ!", zh:"🔺 全部放好了!", es:"🔺 ¡Todo clasificado!", fr:"🔺 Tout est trié !", de:"🔺 Alles einsortiert!", pt:"🔺 Tudo classificado!", ru:"🔺 Всё разложено!", vi:"🔺 Xong hết rồi!", th:"🔺 ใส่ครบแล้ว!", in:"🔺 Semua sudah masuk!" },
play_numline: { ko:"📏 파란 점을 끌어서 자리를 찾아요", en:"📏 Drag the blue dot to the right spot", ja:"📏 青い 点を ドラッグして ばしょを さがそう", zh:"📏 拖动蓝点找到位置", es:"📏 Arrastra el punto azul al lugar correcto", fr:"📏 Fais glisser le point bleu au bon endroit", de:"📏 Zieh den blauen Punkt an die richtige Stelle", pt:"📏 Arraste o ponto azul para o lugar certo", ru:"📏 Перетащи синюю точку в нужное место", vi:"📏 Kéo chấm xanh đến đúng vị trí", th:"📏 ลากจุดสีน้ำเงินไปยังตำแหน่งที่ถูก", in:"📏 Seret titik biru ke posisi yang tepat" },
play_numline_now: { ko:"📏 지금 짚은 곳: %1$s", en:"📏 Pointing at %1$s", ja:"📏 いま さしているところ: %1$s", zh:"📏 现在指着 %1$s", es:"📏 Señalando %1$s", fr:"📏 Pointe sur %1$s", de:"📏 Zeigt auf %1$s", pt:"📏 Apontando para %1$s", ru:"📏 Указывает на %1$s", vi:"📏 Đang chỉ vào %1$s", th:"📏 กำลังชี้ที่ %1$s", in:"📏 Menunjuk %1$s" },
play_angle: { ko:"📐 파란 손잡이를 돌려서 각을 만들어요", en:"📐 Turn the blue handle to make the angle", ja:"📐 青い ハンドルを まわして 角を つくろう", zh:"📐 转动蓝色手柄做出角度", es:"📐 Gira el mando azul para formar el ángulo", fr:"📐 Tourne la poignée bleue pour former l'angle", de:"📐 Dreh den blauen Griff, um den Winkel zu bilden", pt:"📐 Gire o manípulo azul para formar o ângulo", ru:"📐 Поверни синюю ручку, чтобы получить угол", vi:"📐 Xoay tay cầm xanh để tạo góc", th:"📐 หมุนคันโยกสีน้ำเงินเพื่อสร้างมุม", in:"📐 Putar tuas biru untuk membentuk sudut" },
play_angle_now: { ko:"📐 지금 만든 각: %1$d°", en:"📐 Angle now %1$d°", ja:"📐 いまの 角: %1$d°", zh:"📐 现在的角度: %1$d°", es:"📐 Ángulo actual: %1$d°", fr:"📐 Angle actuel : %1$d°", de:"📐 Aktueller Winkel: %1$d°", pt:"📐 Ângulo atual: %1$d°", ru:"📐 Сейчас угол: %1$d°", vi:"📐 Góc hiện tại: %1$d°", th:"📐 มุมตอนนี้: %1$d°", in:"📐 Sudut sekarang: %1$d°" },
play_balance: { ko:"⚖️ 손잡이를 끌어 x 를 바꿔 보세요", en:"⚖️ Drag the handle to change x", ja:"⚖️ ハンドルを ドラッグして x を かえよう", zh:"⚖️ 拖动手柄来改变 x", es:"⚖️ Arrastra el mando para cambiar x", fr:"⚖️ Fais glisser la poignée pour changer x", de:"⚖️ Zieh den Griff, um x zu ändern", pt:"⚖️ Arraste o manípulo para mudar x", ru:"⚖️ Потяни ручку, чтобы изменить x", vi:"⚖️ Kéo tay cầm để đổi x", th:"⚖️ ลากคันโยกเพื่อเปลี่ยน x", in:"⚖️ Seret tuas untuk mengubah x" },
play_balance_now: { ko:"⚖️ 지금 x = %1$d", en:"⚖️ x = %1$d right now", ja:"⚖️ いま x = %1$d", zh:"⚖️ 现在 x = %1$d", es:"⚖️ Ahora x = %1$d", fr:"⚖️ Actuellement x = %1$d", de:"⚖️ Aktuell x = %1$d", pt:"⚖️ Agora x = %1$d", ru:"⚖️ Сейчас x = %1$d", vi:"⚖️ Hiện x = %1$d", th:"⚖️ ตอนนี้ x = %1$d", in:"⚖️ Sekarang x = %1$d" },
play_balance_ok: { ko:"⚖️ x = %1$d — 평형이에요!", en:"⚖️ x = %1$d — it balances!", ja:"⚖️ x = %1$d — つりあった!", zh:"⚖️ x = %1$d — 平衡了!", es:"⚖️ x = %1$d — ¡está equilibrada!", fr:"⚖️ x = %1$d — c'est équilibré !", de:"⚖️ x = %1$d — im Gleichgewicht!", pt:"⚖️ x = %1$d — está equilibrada!", ru:"⚖️ x = %1$d — равновесие!", vi:"⚖️ x = %1$d — cân bằng rồi!", th:"⚖️ x = %1$d — สมดุลแล้ว!", in:"⚖️ x = %1$d — seimbang!" },
play_bar: { ko:"📊 막대를 위로 끌어 올려요", en:"📊 Drag the bars up", ja:"📊 ぼうを 上に ひっぱろう", zh:"📊 把条形往上拖", es:"📊 Arrastra las barras hacia arriba", fr:"📊 Tire les barres vers le haut", de:"📊 Zieh die Balken nach oben", pt:"📊 Arraste as barras para cima", ru:"📊 Потяни столбики вверх", vi:"📊 Kéo các cột lên", th:"📊 ลากแท่งขึ้นด้านบน", in:"📊 Seret batangnya ke atas" },
play_bar_left: { ko:"📊 아직 %1$d개가 안 맞아요", en:"📊 %1$d bars still off", ja:"📊 あと %1$d こ あってない", zh:"📊 还有 %1$d 个不对", es:"📊 %1$d barras aún no coinciden", fr:"📊 %1$d barres pas encore bonnes", de:"📊 %1$d Balken stimmen noch nicht", pt:"📊 %1$d barras ainda erradas", ru:"📊 Ещё %1$d столбиков не совпадают", vi:"📊 Còn %1$d cột chưa đúng", th:"📊 ยังไม่ตรงอีก %1$d แท่ง", in:"📊 %1$d batang belum pas" },
play_bar_done: { ko:"📊 다 맞췄어요!", en:"📊 All bars match!", ja:"📊 ぜんぶ あったよ!", zh:"📊 全部对上了!", es:"📊 ¡Todas coinciden!", fr:"📊 Toutes les barres sont bonnes !", de:"📊 Alle Balken stimmen!", pt:"📊 Todas certas!", ru:"📊 Все столбики совпали!", vi:"📊 Tất cả đã đúng!", th:"📊 ตรงหมดแล้ว!", in:"📊 Semua sudah pas!" },
play_gather: { ko:"👆 %1$s 를 끌어서 %2$s 으로 옮겨요", en:"👆 Drag the %1$s to %2$s", ja:"👆 %1$s を ドラッグして %2$s へ うつそう", zh:"👆 把 %1$s 拖到 %2$s", es:"👆 Arrastra los %1$s a %2$s", fr:"👆 Fais glisser les %1$s vers %2$s", de:"👆 Zieh die %1$s nach %2$s", pt:"👆 Arraste os %1$s para %2$s", ru:"👆 Перетащи %1$s в %2$s", vi:"👆 Kéo %1$s sang %2$s", th:"👆 ลาก %1$s ไปยัง %2$s", in:"👆 Seret %1$s ke %2$s" },
play_gather_now: { ko:"📦 모은 것 %1$d마리 · 아직 %2$d마리", en:"📦 %1$d gathered · %2$d to go", ja:"📦 あつめた %1$d ひき · あと %2$d ひき", zh:"📦 已收集 %1$d 只 · 还剩 %2$d 只", es:"📦 %1$d juntados · faltan %2$d", fr:"📦 %1$d rassemblés · encore %2$d", de:"📦 %1$d gesammelt · noch %2$d", pt:"📦 %1$d juntados · faltam %2$d", ru:"📦 Собрано %1$d · осталось %2$d", vi:"📦 Đã gom %1$d · còn %2$d", th:"📦 รวมแล้ว %1$d · เหลือ %2$d", in:"📦 Terkumpul %1$d · sisa %2$d" },
play_gather_sent: { ko:"📦 보낸 것 %1$d마리 · 남은 것 %2$d마리", en:"📦 %1$d sent · %2$d left", ja:"📦 おくった %1$d ひき · のこり %2$d ひき", zh:"📦 已送走 %1$d 只 · 还剩 %2$d 只", es:"📦 %1$d enviados · quedan %2$d", fr:"📦 %1$d envoyés · %2$d restants", de:"📦 %1$d weggeschickt · %2$d übrig", pt:"📦 %1$d enviados · restam %2$d", ru:"📦 Отправлено %1$d · осталось %2$d", vi:"📦 Đã gửi %1$d · còn %2$d", th:"📦 ส่งไป %1$d · เหลือ %2$d", in:"📦 Dikirim %1$d · sisa %2$d" },

// ---------- 오답 안내 ----------
fb_answer: { ko:"정답: %1$s", en:"Answer: %1$s", ja:"こたえ: %1$s", zh:"答案: %1$s", es:"Respuesta: %1$s", fr:"Réponse : %1$s", de:"Antwort: %1$s", pt:"Resposta: %1$s", ru:"Ответ: %1$s", vi:"Đáp án: %1$s", th:"คำตอบ: %1$s", in:"Jawaban: %1$s" },
fb_answer_time: { ko:"정답: %1$d시 %2$d분", en:"Answer: %1$d:%2$02d", ja:"こたえ: %1$d時 %2$d分", zh:"答案: %1$d 点 %2$d 分", es:"Respuesta: %1$d:%2$02d", fr:"Réponse : %1$d h %2$02d", de:"Antwort: %1$d:%2$02d Uhr", pt:"Resposta: %1$d:%2$02d", ru:"Ответ: %1$d:%2$02d", vi:"Đáp án: %1$d giờ %2$d phút", th:"คำตอบ: %1$d:%2$02d", in:"Jawaban: %1$d:%2$02d" },
fb_sort_wrong: { ko:"%1$d개가 다른 바구니에 들어갔어요.", en:"%1$d went into the wrong basket.", ja:"%1$d こが ちがう かごに 入ったよ。", zh:"有 %1$d 个放错了篮子。", es:"%1$d fueron a la cesta equivocada.", fr:"%1$d sont dans le mauvais panier.", de:"%1$d sind im falschen Korb gelandet.", pt:"%1$d foram para a cesta errada.", ru:"%1$d попали не в ту корзину.", vi:"Có %1$d cái vào sai giỏ.", th:"มี %1$d ชิ้นใส่ผิดตะกร้า", in:"%1$d masuk ke keranjang yang salah." },
fb_bar_wrong: { ko:"%1$d개의 막대 높이가 달라요.", en:"%1$d bars are the wrong height.", ja:"%1$d この ぼうの 高さが ちがうよ。", zh:"有 %1$d 个条形的高度不对。", es:"%1$d barras tienen la altura equivocada.", fr:"%1$d barres n'ont pas la bonne hauteur.", de:"%1$d Balken haben die falsche Höhe.", pt:"%1$d barras estão com altura errada.", ru:"У %1$d столбиков неверная высота.", vi:"Có %1$d cột sai chiều cao.", th:"มี %1$d แท่งที่สูงไม่ถูกต้อง", in:"%1$d batang tingginya salah." },
fb_gather_send: { ko:"%1$s으로 %2$d마리를 보내야 해요. 그러면 %3$d마리가 남아요.", en:"You need to send %2$d to %1$s. Then %3$d are left.", ja:"%1$s へ %2$d ひき おくらないと。のこりは %3$d ひきだよ。", zh:"要送 %2$d 只到%1$s，这样就剩 %3$d 只。", es:"Debes enviar %2$d a %1$s. Entonces quedan %3$d.", fr:"Il faut envoyer %2$d vers %1$s. Il en restera %3$d.", de:"Schick %2$d nach %1$s. Dann bleiben %3$d.", pt:"Você precisa enviar %2$d para %1$s. Sobram %3$d.", ru:"Нужно отправить %2$d в %1$s. Останется %3$d.", vi:"Cần gửi %2$d sang %1$s. Khi đó còn %3$d.", th:"ต้องส่ง %2$d ไปที่ %1$s แล้วจะเหลือ %3$d", in:"Kirim %2$d ke %1$s. Sisanya %3$d." },
fb_gather_all: { ko:"%1$d마리를 모두 모아야 해요.", en:"You need to gather all %1$d.", ja:"%1$d ひき ぜんぶ あつめないとね。", zh:"要把 %1$d 只全部收集起来。", es:"Tienes que juntar los %1$d.", fr:"Il faut tous les rassembler : %1$d.", de:"Du musst alle %1$d sammeln.", pt:"Você precisa juntar todos os %1$d.", ru:"Нужно собрать все %1$d.", vi:"Cần gom đủ %1$d.", th:"ต้องรวมให้ครบ %1$d", in:"Kamu harus mengumpulkan semua %1$d." },
fb_paint_over: { ko:"%1$d칸을 더 칠했어요. 정답: %2$d / %3$d", en:"You coloured %1$d too many. Answer: %2$d / %3$d", ja:"%1$d こ ぬりすぎだよ。こたえ: %2$d / %3$d", zh:"多涂了 %1$d 格。答案: %2$d / %3$d", es:"Coloreaste %1$d de más. Respuesta: %2$d / %3$d", fr:"Tu en as colorié %1$d de trop. Réponse : %2$d / %3$d", de:"%1$d zu viel gefärbt. Antwort: %2$d / %3$d", pt:"Você pintou %1$d a mais. Resposta: %2$d / %3$d", ru:"Закрашено на %1$d больше. Ответ: %2$d / %3$d", vi:"Bạn tô thừa %1$d ô. Đáp án: %2$d / %3$d", th:"ระบายเกินไป %1$d ช่อง คำตอบ: %2$d / %3$d", in:"Kamu mewarnai %1$d terlalu banyak. Jawaban: %2$d / %3$d" },
fb_paint_under: { ko:"%1$d칸 더 칠해야 해요. 정답: %2$d / %3$d", en:"You need %1$d more coloured. Answer: %2$d / %3$d", ja:"あと %1$d こ ぬろう。こたえ: %2$d / %3$d", zh:"还要再涂 %1$d 格。答案: %2$d / %3$d", es:"Faltan %1$d por colorear. Respuesta: %2$d / %3$d", fr:"Il en manque %1$d à colorier. Réponse : %2$d / %3$d", de:"Noch %1$d färben. Antwort: %2$d / %3$d", pt:"Faltam %1$d para pintar. Resposta: %2$d / %3$d", ru:"Нужно закрасить ещё %1$d. Ответ: %2$d / %3$d", vi:"Cần tô thêm %1$d ô. Đáp án: %2$d / %3$d", th:"ต้องระบายอีก %1$d ช่อง คำตอบ: %2$d / %3$d", in:"Perlu %1$d lagi diwarnai. Jawaban: %2$d / %3$d" },
fb_group_uneven: { ko:"바구니마다 개수가 같아야 해요. 정답: 한 바구니에 %1$d개", en:"Every basket must have the same number. Answer: %1$d per basket", ja:"かごごとに 同じ かずに しよう。こたえ: 1つの かごに %1$d こ", zh:"每个篮子的数量要一样。答案: 每篮 %1$d 个", es:"Cada cesta debe tener lo mismo. Respuesta: %1$d por cesta", fr:"Chaque panier doit en avoir autant. Réponse : %1$d par panier", de:"Jeder Korb muss gleich viele haben. Antwort: %1$d pro Korb", pt:"Cada cesta deve ter a mesma quantidade. Resposta: %1$d por cesta", ru:"В каждой корзине должно быть поровну. Ответ: по %1$d", vi:"Mỗi giỏ phải bằng nhau. Đáp án: %1$d mỗi giỏ", th:"แต่ละตะกร้าต้องเท่ากัน คำตอบ: ตะกร้าละ %1$d", in:"Tiap keranjang harus sama. Jawaban: %1$d per keranjang" },
fb_group_left: { ko:"아직 다 담지 않았어요. 정답: 한 바구니에 %1$d개", en:"Not everything is in yet. Answer: %1$d per basket", ja:"まだ ぜんぶ 入れてないよ。こたえ: 1つの かごに %1$d こ", zh:"还没全部放进去。答案: 每篮 %1$d 个", es:"Todavía falta poner algunos. Respuesta: %1$d por cesta", fr:"Il en reste à ranger. Réponse : %1$d par panier", de:"Es fehlt noch etwas. Antwort: %1$d pro Korb", pt:"Ainda falta colocar alguns. Resposta: %1$d por cesta", ru:"Ещё не всё разложено. Ответ: по %1$d", vi:"Vẫn chưa xếp hết. Đáp án: %1$d mỗi giỏ", th:"ยังใส่ไม่ครบ คำตอบ: ตะกร้าละ %1$d", in:"Belum semuanya masuk. Jawaban: %1$d per keranjang" },
fb_angle_wider: { ko:"조금 더 벌려야 해요. 정답: %1$d°", en:"Open it a bit wider. Answer: %1$d°", ja:"もう すこし 広げよう。こたえ: %1$d°", zh:"再张开一点。答案: %1$d°", es:"Ábrelo un poco más. Respuesta: %1$d°", fr:"Ouvre un peu plus. Réponse : %1$d°", de:"Etwas weiter öffnen. Antwort: %1$d°", pt:"Abra um pouco mais. Resposta: %1$d°", ru:"Раскрой чуть шире. Ответ: %1$d°", vi:"Mở rộng thêm chút nữa. Đáp án: %1$d°", th:"กางออกอีกนิด คำตอบ: %1$d°", in:"Buka sedikit lebih lebar. Jawaban: %1$d°" },
fb_angle_narrower: { ko:"조금 더 좁혀야 해요. 정답: %1$d°", en:"Close it a bit more. Answer: %1$d°", ja:"もう すこし せばめよう。こたえ: %1$d°", zh:"再收窄一点。答案: %1$d°", es:"Ciérralo un poco más. Respuesta: %1$d°", fr:"Referme un peu. Réponse : %1$d°", de:"Etwas enger machen. Antwort: %1$d°", pt:"Feche um pouco mais. Resposta: %1$d°", ru:"Сведи чуть уже. Ответ: %1$d°", vi:"Thu hẹp thêm chút nữa. Đáp án: %1$d°", th:"หุบเข้าอีกนิด คำตอบ: %1$d°", in:"Rapatkan sedikit lagi. Jawaban: %1$d°" },
fb_balance: { ko:"저울이 평형이 되는 값은 x = %1$d 이에요.", en:"The scale balances when x = %1$d.", ja:"てんびんが つりあうのは x = %1$d のときだよ。", zh:"当 x = %1$d 时天平才平衡。", es:"La balanza se equilibra con x = %1$d.", fr:"La balance s'équilibre quand x = %1$d.", de:"Die Waage ist bei x = %1$d im Gleichgewicht.", pt:"A balança equilibra com x = %1$d.", ru:"Весы уравновешиваются при x = %1$d.", vi:"Cân thăng bằng khi x = %1$d.", th:"ตาชั่งสมดุลเมื่อ x = %1$d", in:"Timbangan seimbang saat x = %1$d." },

// ---------- 칭찬 · 격려 ----------
praise_correct: { ko:"삐약! 정답이에요!", en:"Yes! That's right!", ja:"ピヨッ! せいかい!", zh:"啾! 答对了!", es:"¡Sí! ¡Correcto!", fr:"Oui ! C'est juste !", de:"Ja! Richtig!", pt:"Isso! Certinho!", ru:"Да! Верно!", vi:"Đúng rồi!", th:"ถูกต้อง!", in:"Benar sekali!" },
praise_nice: { ko:"삐약삐약~ 좋아요!", en:"Nice one!", ja:"ピヨピヨ〜 いいね!", zh:"啾啾~ 很棒!", es:"¡Muy bien!", fr:"Bien joué !", de:"Sehr schön!", pt:"Muito bem!", ru:"Отлично!", vi:"Giỏi lắm!", th:"เก่งมาก!", in:"Bagus!" },
praise_great: { ko:"굿굿! 최고예요!", en:"Great job!", ja:"グッド! さいこう!", zh:"太棒了!", es:"¡Genial!", fr:"Super !", de:"Klasse!", pt:"Ótimo!", ru:"Здорово!", vi:"Tuyệt vời!", th:"ยอดเยี่ยม!", in:"Hebat!" },
praise_genius: { ko:"역시 천재!", en:"You're a genius!", ja:"やっぱり てんさい!", zh:"真是天才!", es:"¡Eres un genio!", fr:"Tu es un génie !", de:"Du bist ein Genie!", pt:"Você é um gênio!", ru:"Ты гений!", vi:"Bạn thật thông minh!", th:"อัจฉริยะจริง ๆ!", in:"Kamu jenius!" },
praise_perfect: { ko:"완벽해요! 🐥", en:"Perfect! 🐥", ja:"かんぺき! 🐥", zh:"完美! 🐥", es:"¡Perfecto! 🐥", fr:"Parfait ! 🐥", de:"Perfekt! 🐥", pt:"Perfeito! 🐥", ru:"Идеально! 🐥", vi:"Hoàn hảo! 🐥", th:"สมบูรณ์แบบ! 🐥", in:"Sempurna! 🐥" },
cheer_next: { ko:"삐약… 다음엔 맞혀요!", en:"Aw… you'll get the next one!", ja:"ピヨ… つぎは あてよう!", zh:"啾… 下次一定对!", es:"Uy… ¡la próxima la aciertas!", fr:"Oh… tu auras la prochaine !", de:"Oh… die nächste klappt!", pt:"Ah… você acerta a próxima!", ru:"Ой… в следующий раз получится!", vi:"Ồ… lần sau sẽ đúng!", th:"อุ๊ย… ครั้งหน้าต้องถูก!", in:"Aduh… lain kali pasti bisa!" },
cheer_again: { ko:"괜찮아요, 다시 나와요!", en:"It's okay — it'll come back!", ja:"だいじょうぶ、また 出てくるよ!", zh:"没关系，还会再出现的!", es:"No pasa nada, volverá a salir.", fr:"Pas grave, elle reviendra !", de:"Kein Problem, die kommt wieder!", pt:"Tudo bem, ela volta!", ru:"Ничего, она ещё встретится!", vi:"Không sao, câu này sẽ quay lại!", th:"ไม่เป็นไร เดี๋ยวเจอใหม่!", in:"Tidak apa-apa, nanti muncul lagi!" },
cheer_more: { ko:"조금만 더 힘내요!", en:"Keep going, almost there!", ja:"もう すこし がんばろう!", zh:"再加把劲!", es:"¡Ánimo, ya casi!", fr:"Courage, tu y es presque !", de:"Weiter so, fast geschafft!", pt:"Continue, quase lá!", ru:"Ещё немного, почти получилось!", vi:"Cố lên, sắp được rồi!", th:"สู้ ๆ ใกล้แล้ว!", in:"Ayo terus, hampir bisa!" },
cheer_close: { ko:"아쉬워요 😢", en:"So close 😢", ja:"おしい 😢", zh:"差一点 😢", es:"Casi 😢", fr:"Presque 😢", de:"Knapp daneben 😢", pt:"Quase 😢", ru:"Почти 😢", vi:"Suýt nữa rồi 😢", th:"เกือบแล้ว 😢", in:"Hampir 😢" },

// ---------- 결과 · 대화상자 ----------
lesson_no_review: { ko:"복습할 오답이 없어요! 🐥", en:"No wrong answers to review! 🐥", ja:"ふくしゅうする まちがいが ないよ! 🐥", zh:"没有需要复习的错题! 🐥", es:"¡No hay errores que repasar! 🐥", fr:"Aucune erreur à revoir ! 🐥", de:"Keine Fehler zum Wiederholen! 🐥", pt:"Nenhum erro para revisar! 🐥", ru:"Нет ошибок для повторения! 🐥", vi:"Không có câu sai nào để ôn! 🐥", th:"ไม่มีข้อผิดให้ทบทวน! 🐥", in:"Tidak ada kesalahan untuk diulang! 🐥" },
heart_empty_title: { ko:"하트가 없어요 💔", en:"Out of hearts 💔", ja:"ハートが ないよ 💔", zh:"爱心用完了 💔", es:"Sin corazones 💔", fr:"Plus de cœurs 💔", de:"Keine Herzen mehr 💔", pt:"Sem corações 💔", ru:"Сердечки закончились 💔", vi:"Hết tim rồi 💔", th:"หัวใจหมดแล้ว 💔", in:"Hati habis 💔" },
heart_empty_msg: { ko:"30분마다 하트가 1개씩 차요.\n오답 복습을 완료하면 하트 1개를 받을 수 있어요!", en:"You get one heart back every 30 minutes.\nFinish a review session to earn one right away!", ja:"30分ごとに ハートが 1つ たまるよ。\nまちがい ふくしゅうを おえると 1つ もらえる!", zh:"每30分钟回复1颗爱心。\n完成错题复习就能马上得到1颗!", es:"Recuperas un corazón cada 30 minutos.\n¡Completa un repaso para conseguir uno ya!", fr:"Tu récupères un cœur toutes les 30 minutes.\nTermine une révision pour en gagner un tout de suite !", de:"Alle 30 Minuten gibt es ein Herz zurück.\nSchließe eine Wiederholung ab und bekomme sofort eins!", pt:"Você recupera um coração a cada 30 minutos.\nComplete uma revisão para ganhar um agora!", ru:"Одно сердечко возвращается каждые 30 минут.\nЗаверши повторение и получи сердечко сразу!", vi:"Cứ 30 phút bạn được hồi 1 tim.\nHoàn thành ôn tập để nhận ngay 1 tim!", th:"หัวใจจะเพิ่ม 1 ดวงทุก 30 นาที\nทบทวนข้อผิดให้จบเพื่อรับทันที 1 ดวง!", in:"Satu hati pulih setiap 30 menit.\nSelesaikan ulasan untuk langsung dapat satu!" },
result_no_heart_title: { ko:"하트가 다 떨어졌어요 💔", en:"You've run out of hearts 💔", ja:"ハートが なくなったよ 💔", zh:"爱心用完了 💔", es:"Te quedaste sin corazones 💔", fr:"Tu n'as plus de cœurs 💔", de:"Deine Herzen sind aufgebraucht 💔", pt:"Seus corações acabaram 💔", ru:"Сердечки закончились 💔", vi:"Bạn đã hết tim 💔", th:"หัวใจหมดแล้ว 💔", in:"Hatimu habis 💔" },
result_no_heart_msg: { ko:"오답 복습으로 하트를 채우고\n다시 도전해 봐요!", en:"Review your mistakes to refill hearts\nand try again!", ja:"まちがい ふくしゅうで ハートを ためて\nまた ちょうせんしよう!", zh:"通过复习错题补充爱心\n再来挑战吧!", es:"Repasa tus errores para recuperar corazones\n¡y vuelve a intentarlo!", fr:"Révise tes erreurs pour regagner des cœurs\net réessaie !", de:"Wiederhole deine Fehler, um Herzen zu füllen\nund versuch es noch mal!", pt:"Revise seus erros para recuperar corações\ne tente de novo!", ru:"Повтори ошибки, чтобы вернуть сердечки,\nи попробуй снова!", vi:"Ôn lại câu sai để hồi tim\nrồi thử lại nhé!", th:"ทบทวนข้อผิดเพื่อเติมหัวใจ\nแล้วลองใหม่!", in:"Ulangi kesalahanmu untuk mengisi hati\nlalu coba lagi!" },
result_review_title: { ko:"복습 완료! 💊", en:"Review done! 💊", ja:"ふくしゅう かんりょう! 💊", zh:"复习完成! 💊", es:"¡Repaso terminado! 💊", fr:"Révision terminée ! 💊", de:"Wiederholung fertig! 💊", pt:"Revisão concluída! 💊", ru:"Повторение завершено! 💊", vi:"Ôn tập xong! 💊", th:"ทบทวนเสร็จแล้ว! 💊", in:"Ulasan selesai! 💊" },
result_lesson_title: { ko:"레슨 완료! 🎉", en:"Lesson complete! 🎉", ja:"レッスン かんりょう! 🎉", zh:"课程完成! 🎉", es:"¡Lección completada! 🎉", fr:"Leçon terminée ! 🎉", de:"Lektion geschafft! 🎉", pt:"Lição concluída! 🎉", ru:"Урок пройден! 🎉", vi:"Hoàn thành bài học! 🎉", th:"เรียนจบบทแล้ว! 🎉", in:"Pelajaran selesai! 🎉" },
result_perfect_title: { ko:"퍼펙트! 💯", en:"Perfect! 💯", ja:"パーフェクト! 💯", zh:"满分! 💯", es:"¡Perfecto! 💯", fr:"Parfait ! 💯", de:"Perfekt! 💯", pt:"Perfeito! 💯", ru:"Идеально! 💯", vi:"Tuyệt đối! 💯", th:"เต็ม! 💯", in:"Sempurna! 💯" },
review_cleared: { ko:"이 오답은 완전히 클리어! 💊✨", en:"This one is fully cleared! 💊✨", ja:"この まちがいは かんぜん クリア! 💊✨", zh:"这道错题完全攻克了! 💊✨", es:"¡Este error está superado! 💊✨", fr:"Cette erreur est complètement corrigée ! 💊✨", de:"Dieser Fehler ist ganz erledigt! 💊✨", pt:"Este erro foi totalmente superado! 💊✨", ru:"Эта ошибка полностью закрыта! 💊✨", vi:"Câu sai này đã xử lý xong! 💊✨", th:"ข้อผิดนี้ผ่านแล้ว! 💊✨", in:"Kesalahan ini sudah tuntas! 💊✨" },
review_one_more: { ko:"좋아요! 한 번 더 맞히면 클리어!", en:"Nice! One more correct and it's cleared!", ja:"いいね! もう 1かい あてたら クリア!", zh:"很好! 再答对一次就攻克了!", es:"¡Bien! Una más correcta y queda superado.", fr:"Bien ! Encore une bonne réponse et c'est réglé.", de:"Gut! Noch einmal richtig und es ist erledigt.", pt:"Boa! Mais um acerto e está resolvido.", ru:"Отлично! Ещё один верный ответ — и готово.", vi:"Tốt! Đúng thêm một lần nữa là xong.", th:"ดีมาก! ถูกอีกครั้งก็ผ่านแล้ว", in:"Bagus! Satu benar lagi dan tuntas." },
review_mode: { ko:"오답 복습", en:"Review", ja:"まちがい ふくしゅう", zh:"错题复习", es:"Repaso", fr:"Révision", de:"Wiederholung", pt:"Revisão", ru:"Повторение", vi:"Ôn tập", th:"ทบทวน", in:"Ulasan" },
review_done: { ko:"오답 복습 완료", en:"Review finished", ja:"ふくしゅう かんりょう", zh:"错题复习完成", es:"Repaso terminado", fr:"Révision terminée", de:"Wiederholung fertig", pt:"Revisão concluída", ru:"Повторение завершено", vi:"Đã ôn xong", th:"ทบทวนเสร็จแล้ว", in:"Ulasan selesai" },
goal_reached: { ko:"오늘의 목표 달성", en:"Daily goal reached", ja:"きょうの もくひょう たっせい", zh:"达成今日目标", es:"Meta diaria lograda", fr:"Objectif du jour atteint", de:"Tagesziel erreicht", pt:"Meta do dia alcançada", ru:"Цель дня достигнута", vi:"Đạt mục tiêu hôm nay", th:"บรรลุเป้าหมายวันนี้", in:"Target harian tercapai" },
badge_earned: { ko:"🏆 배지 획득: %1$s %2$s!", en:"🏆 Badge earned: %1$s %2$s!", ja:"🏆 バッジ ゲット: %1$s %2$s!", zh:"🏆 获得徽章: %1$s %2$s!", es:"🏆 Insignia conseguida: %1$s %2$s!", fr:"🏆 Badge obtenu : %1$s %2$s !", de:"🏆 Abzeichen erhalten: %1$s %2$s!", pt:"🏆 Distintivo conquistado: %1$s %2$s!", ru:"🏆 Получен значок: %1$s %2$s!", vi:"🏆 Nhận huy hiệu: %1$s %2$s!", th:"🏆 ได้รับเหรียญ: %1$s %2$s!", in:"🏆 Lencana didapat: %1$s %2$s!" },
clear: { ko:"지우기", en:"Clear", ja:"けす", zh:"清除", es:"Borrar", fr:"Effacer", de:"Löschen", pt:"Limpar", ru:"Стереть", vi:"Xóa", th:"ล้าง", in:"Hapus" },

};
