/**
 * 마지막 남은 화면 문자열 — 결과 요약, 홈, 그림 뷰 안내, 병아리 응원.
 */
module.exports = {

// ---------- 결과 화면 ----------
result_review_stats: { ko:"정답률 %1$d%% · +%2$d XP\n하트 1개 회복! ❤️ %3$d", en:"%1$d%% correct · +%2$d XP\nOne heart restored! ❤️ %3$d", ja:"せいかいりつ %1$d%% · +%2$d XP\nハート 1つ かいふく! ❤️ %3$d", zh:"正确率 %1$d%% · +%2$d XP\n恢复1颗爱心! ❤️ %3$d", es:"%1$d%% de acierto · +%2$d XP\n¡Un corazón recuperado! ❤️ %3$d", fr:"%1$d%% de réussite · +%2$d XP\nUn cœur récupéré ! ❤️ %3$d", de:"%1$d%% richtig · +%2$d XP\nEin Herz zurück! ❤️ %3$d", pt:"%1$d%% de acerto · +%2$d XP\nUm coração recuperado! ❤️ %3$d", ru:"Точность %1$d%% · +%2$d XP\nВосстановлено сердечко! ❤️ %3$d", vi:"Đúng %1$d%% · +%2$d XP\nHồi 1 tim! ❤️ %3$d", th:"ถูก %1$d%% · +%2$d XP\nได้หัวใจคืน 1 ดวง! ❤️ %3$d", in:"Benar %1$d%% · +%2$d XP\nSatu hati pulih! ❤️ %3$d" },
result_lesson_sub: { ko:"%1$s (첫 시도 정답 %2$d문제)", en:"%1$s (%2$d right on the first try)", ja:"%1$s (1かいめで せいかい %2$d もん)", zh:"%1$s (首次就答对 %2$d 题)", es:"%1$s (%2$d acertadas al primer intento)", fr:"%1$s (%2$d justes du premier coup)", de:"%1$s (%2$d beim ersten Versuch richtig)", pt:"%1$s (%2$d certas na primeira tentativa)", ru:"%1$s (верно с первой попытки: %2$d)", vi:"%1$s (%2$d câu đúng ngay lần đầu)", th:"%1$s (ถูกตั้งแต่ครั้งแรก %2$d ข้อ)", in:"%1$s (%2$d benar di percobaan pertama)" },
result_perfect_bonus: { ko:" (퍼펙트 +5 포함)", en:" (includes +5 perfect bonus)", ja:" (パーフェクト +5 こみ)", zh:" (含满分奖励 +5)", es:" (incluye +5 por perfecto)", fr:" (bonus parfait +5 inclus)", de:" (inkl. +5 Perfekt-Bonus)", pt:" (inclui +5 de bônus perfeito)", ru:" (включая +5 за идеал)", vi:" (đã gồm +5 thưởng hoàn hảo)", th:" (รวมโบนัสเต็ม +5)", in:" (termasuk bonus sempurna +5)" },
result_coins: { ko:"💰 용돈 +%1$s  (지갑 %2$s)", en:"💰 Pocket money +%1$s  (wallet %2$s)", ja:"💰 おこづかい +%1$s  (さいふ %2$s)", zh:"💰 零花钱 +%1$s  (钱包 %2$s)", es:"💰 Dinero +%1$s  (cartera %2$s)", fr:"💰 Argent +%1$s  (portefeuille %2$s)", de:"💰 Taschengeld +%1$s  (Geldbeutel %2$s)", pt:"💰 Mesada +%1$s  (carteira %2$s)", ru:"💰 Карманные +%1$s  (кошелёк %2$s)", vi:"💰 Tiền tiêu vặt +%1$s  (ví %2$s)", th:"💰 เงินสะสม +%1$s  (กระเป๋า %2$s)", in:"💰 Uang saku +%1$s  (dompet %2$s)" },
result_no_coins: { ko:"💰 이미 깬 레슨이라 용돈은 없어요", en:"💰 No pocket money — you already cleared this lesson", ja:"💰 もう クリアした レッスンなので おこづかいは なしだよ", zh:"💰 这课已经通关过，没有零花钱", es:"💰 Sin dinero: ya habías superado esta lección", fr:"💰 Pas d'argent : leçon déjà réussie", de:"💰 Kein Taschengeld — Lektion war schon geschafft", pt:"💰 Sem mesada — você já tinha concluído esta lição", ru:"💰 Без карманных — урок уже пройден", vi:"💰 Không có tiền — bài này đã hoàn thành rồi", th:"💰 ไม่มีเงินสะสม เพราะผ่านบทนี้ไปแล้ว", in:"💰 Tanpa uang saku — pelajaran ini sudah selesai" },
result_skill_up: { ko:"🎉 %1$s %2$s 실력이 Lv.%3$d 로 올랐어요!", en:"🎉 Your %1$s %2$s skill rose to Lv.%3$d!", ja:"🎉 %1$s %2$s の じつりょくが Lv.%3$d に あがったよ!", zh:"🎉 %1$s %2$s 能力升到 Lv.%3$d 了!", es:"🎉 ¡Tu habilidad %1$s %2$s subió a Nv.%3$d!", fr:"🎉 Ta compétence %1$s %2$s passe au niv.%3$d !", de:"🎉 Deine %1$s %2$s-Fähigkeit ist auf Level %3$d gestiegen!", pt:"🎉 Sua habilidade %1$s %2$s subiu para Nv.%3$d!", ru:"🎉 Навык %1$s %2$s вырос до ур.%3$d!", vi:"🎉 Kỹ năng %1$s %2$s lên cấp %3$d!", th:"🎉 ทักษะ %1$s %2$s เลื่อนเป็น Lv.%3$d!", in:"🎉 Kemampuan %1$s %2$s naik ke Lv.%3$d!" },
result_rank_up: { ko:"👑 칭호 승급! %1$s %2$s", en:"👑 New title! %1$s %2$s", ja:"👑 しょうごう アップ! %1$s %2$s", zh:"👑 称号升级! %1$s %2$s", es:"👑 ¡Nuevo título! %1$s %2$s", fr:"👑 Nouveau titre ! %1$s %2$s", de:"👑 Neuer Titel! %1$s %2$s", pt:"👑 Novo título! %1$s %2$s", ru:"👑 Новое звание! %1$s %2$s", vi:"👑 Danh hiệu mới! %1$s %2$s", th:"👑 เลื่อนฉายา! %1$s %2$s", in:"👑 Gelar baru! %1$s %2$s" },
result_goal: { ko:"🎯 오늘의 목표 %1$d / %2$d XP", en:"🎯 Today's goal %1$d / %2$d XP", ja:"🎯 きょうの もくひょう %1$d / %2$d XP", zh:"🎯 今日目标 %1$d / %2$d XP", es:"🎯 Meta de hoy %1$d / %2$d XP", fr:"🎯 Objectif du jour %1$d / %2$d XP", de:"🎯 Tagesziel %1$d / %2$d XP", pt:"🎯 Meta de hoje %1$d / %2$d XP", ru:"🎯 Цель дня %1$d / %2$d XP", vi:"🎯 Mục tiêu hôm nay %1$d / %2$d XP", th:"🎯 เป้าหมายวันนี้ %1$d / %2$d XP", in:"🎯 Target hari ini %1$d / %2$d XP" },
result_goal_done: { ko:"  ✅ 달성!", en:"  ✅ Done!", ja:"  ✅ たっせい!", zh:"  ✅ 达成!", es:"  ✅ ¡Logrado!", fr:"  ✅ Atteint !", de:"  ✅ Geschafft!", pt:"  ✅ Alcançada!", ru:"  ✅ Достигнута!", vi:"  ✅ Đạt rồi!", th:"  ✅ สำเร็จ!", in:"  ✅ Tercapai!" },
result_goal_bonus: { ko:"💰 목표 달성 보너스 +%1$s", en:"💰 Goal bonus +%1$s", ja:"💰 もくひょう たっせい ボーナス +%1$s", zh:"💰 达成目标奖励 +%1$s", es:"💰 Bono por la meta +%1$s", fr:"💰 Bonus d'objectif +%1$s", de:"💰 Zielbonus +%1$s", pt:"💰 Bônus de meta +%1$s", ru:"💰 Бонус за цель +%1$s", vi:"💰 Thưởng đạt mục tiêu +%1$s", th:"💰 โบนัสบรรลุเป้าหมาย +%1$s", in:"💰 Bonus target +%1$s" },

// ---------- 홈 ----------
goal_light: { ko:"가볍게 (레슨 1개쯤)", en:"Light (about 1 lesson)", ja:"かるく (レッスン 1こくらい)", zh:"轻松 (约1课)", es:"Suave (1 lección)", fr:"Léger (environ 1 leçon)", de:"Locker (etwa 1 Lektion)", pt:"Leve (cerca de 1 lição)", ru:"Легко (около 1 урока)", vi:"Nhẹ nhàng (khoảng 1 bài)", th:"เบา ๆ (ราว 1 บท)", in:"Ringan (sekitar 1 pelajaran)" },
goal_normal: { ko:"보통 (레슨 2~3개)", en:"Normal (2–3 lessons)", ja:"ふつう (レッスン 2〜3こ)", zh:"普通 (2~3课)", es:"Normal (2-3 lecciones)", fr:"Normal (2 à 3 leçons)", de:"Normal (2–3 Lektionen)", pt:"Normal (2 a 3 lições)", ru:"Обычно (2–3 урока)", vi:"Vừa phải (2–3 bài)", th:"ปานกลาง (2–3 บท)", in:"Sedang (2–3 pelajaran)" },
goal_hard: { ko:"열심히 (레슨 5개쯤)", en:"Hard (about 5 lessons)", ja:"がんばる (レッスン 5こくらい)", zh:"努力 (约5课)", es:"Intenso (unas 5 lecciones)", fr:"Intense (environ 5 leçons)", de:"Fleißig (etwa 5 Lektionen)", pt:"Puxado (cerca de 5 lições)", ru:"Усердно (около 5 уроков)", vi:"Chăm chỉ (khoảng 5 bài)", th:"ขยัน (ราว 5 บท)", in:"Rajin (sekitar 5 pelajaran)" },
goal_beast: { ko:"빡세게 (레슨 10개쯤)", en:"Beast mode (about 10 lessons)", ja:"ハード (レッスン 10こくらい)", zh:"硬核 (约10课)", es:"Modo bestia (unas 10 lecciones)", fr:"Mode bête (environ 10 leçons)", de:"Vollgas (etwa 10 Lektionen)", pt:"Modo fera (cerca de 10 lições)", ru:"На максимум (около 10 уроков)", vi:"Cực chăm (khoảng 10 bài)", th:"โหดสุด (ราว 10 บท)", in:"Mode gaspol (sekitar 10 pelajaran)" },
home_placement_math: { ko:"레벨테스트로 내 학년 찾기!\n25문제로 딱 맞는 단계를 정해줘요", en:"Find your grade with a placement test!\n25 questions pick the right level for you", ja:"レベルテストで じぶんの がくねんを さがそう!\n25もんで ぴったりの だんかいを きめるよ", zh:"用分级测试找到适合的年级!\n25道题为你定好合适的阶段", es:"¡Encuentra tu curso con la prueba de nivel!\n25 preguntas eligen el nivel exacto", fr:"Trouve ton niveau avec le test !\n25 questions choisissent l'étape qui te convient", de:"Finde deine Klassenstufe mit dem Einstufungstest!\n25 Fragen bestimmen die passende Stufe", pt:"Descubra seu ano com o teste de nível!\n25 questões escolhem o estágio certo", ru:"Найди свой класс с помощью теста!\n25 вопросов подберут подходящий уровень", vi:"Tìm đúng lớp bằng bài kiểm tra trình độ!\n25 câu sẽ chọn giai đoạn phù hợp", th:"หาระดับชั้นของคุณด้วยแบบทดสอบ!\n25 ข้อจะเลือกขั้นที่เหมาะสมให้", in:"Temukan tingkatmu lewat tes penempatan!\n25 soal memilih tahap yang pas" },
rank_next: { ko:"  →  다음 칭호 %1$s %2$s", en:"  →  Next title %1$s %2$s", ja:"  →  つぎの しょうごう %1$s %2$s", zh:"  →  下一个称号 %1$s %2$s", es:"  →  Siguiente título %1$s %2$s", fr:"  →  Titre suivant %1$s %2$s", de:"  →  Nächster Titel %1$s %2$s", pt:"  →  Próximo título %1$s %2$s", ru:"  →  Следующее звание %1$s %2$s", vi:"  →  Danh hiệu tiếp theo %1$s %2$s", th:"  →  ฉายาถัดไป %1$s %2$s", in:"  →  Gelar berikutnya %1$s %2$s" },
rank_next_short: { ko:"  (→ %1$s Lv.%2$.1f)", en:"  (→ %1$s Lv.%2$.1f)", ja:"  (→ %1$s Lv.%2$.1f)", zh:"  (→ %1$s Lv.%2$.1f)", es:"  (→ %1$s Nv.%2$.1f)", fr:"  (→ %1$s niv.%2$.1f)", de:"  (→ %1$s Lv.%2$.1f)", pt:"  (→ %1$s Nv.%2$.1f)", ru:"  (→ %1$s ур.%2$.1f)", vi:"  (→ %1$s cấp %2$.1f)", th:"  (→ %1$s Lv.%2$.1f)", in:"  (→ %1$s Lv.%2$.1f)" },
rank_top: { ko:"  (최고 칭호!)", en:"  (top title!)", ja:"  (さいこうの しょうごう!)", zh:"  (最高称号!)", es:"  (¡título máximo!)", fr:"  (titre suprême !)", de:"  (höchster Titel!)", pt:"  (título máximo!)", ru:"  (высшее звание!)", vi:"  (danh hiệu cao nhất!)", th:"  (ฉายาสูงสุด!)", in:"  (gelar tertinggi!)" },
weak_area: { ko:"약한 영역: %1$s %2$s", en:"Weakest area: %1$s %2$s", ja:"よわい りょういき: %1$s %2$s", zh:"薄弱领域: %1$s %2$s", es:"Área más floja: %1$s %2$s", fr:"Point faible : %1$s %2$s", de:"Schwächster Bereich: %1$s %2$s", pt:"Área mais fraca: %1$s %2$s", ru:"Слабая область: %1$s %2$s", vi:"Điểm yếu: %1$s %2$s", th:"จุดอ่อน: %1$s %2$s", in:"Bidang terlemah: %1$s %2$s" },
not_started: { ko:"  시작 전", en:"  Not started", ja:"  まだ", zh:"  未开始", es:"  Sin empezar", fr:"  Pas commencé", de:"  Noch nicht begonnen", pt:"  Não iniciado", ru:"  Не начато", vi:"  Chưa bắt đầu", th:"  ยังไม่เริ่ม", in:"  Belum dimulai" },
locked_lesson: { ko:"앞의 레슨을 먼저 완료해 주세요! 🥚", en:"Finish the earlier lessons first! 🥚", ja:"まえの レッスンを さきに おわらせてね! 🥚", zh:"请先完成前面的课程! 🥚", es:"¡Termina antes las lecciones anteriores! 🥚", fr:"Termine d'abord les leçons précédentes ! 🥚", de:"Schließe zuerst die vorherigen Lektionen ab! 🥚", pt:"Conclua as lições anteriores primeiro! 🥚", ru:"Сначала пройди предыдущие уроки! 🥚", vi:"Hãy hoàn thành các bài trước đã! 🥚", th:"เรียนบทก่อนหน้าให้จบก่อนนะ! 🥚", in:"Selesaikan pelajaran sebelumnya dulu! 🥚" },
copied: { ko:"복사했어요", en:"Copied", ja:"コピーしたよ", zh:"已复制", es:"Copiado", fr:"Copié", de:"Kopiert", pt:"Copiado", ru:"Скопировано", vi:"Đã sao chép", th:"คัดลอกแล้ว", in:"Tersalin" },

// ---------- 레벨테스트 ----------
placement_done: { ko:"%1$s 레벨테스트 완료", en:"%1$s placement test done", ja:"%1$s レベルテスト かんりょう", zh:"%1$s 分级测试完成", es:"Prueba de nivel de %1$s completada", fr:"Test de niveau de %1$s terminé", de:"%1$s-Einstufungstest fertig", pt:"Teste de nível de %1$s concluído", ru:"Тест уровня по предмету «%1$s» завершён", vi:"Hoàn thành bài kiểm tra trình độ %1$s", th:"ทำแบบทดสอบระดับ %1$s เสร็จแล้ว", in:"Tes penempatan %1$s selesai" },
placement_coins: { ko:"💰 용돈 +%1$s", en:"💰 Pocket money +%1$s", ja:"💰 おこづかい +%1$s", zh:"💰 零花钱 +%1$s", es:"💰 Dinero +%1$s", fr:"💰 Argent +%1$s", de:"💰 Taschengeld +%1$s", pt:"💰 Mesada +%1$s", ru:"💰 Карманные +%1$s", vi:"💰 Tiền tiêu vặt +%1$s", th:"💰 เงินสะสม +%1$s", in:"💰 Uang saku +%1$s" },
placement_msg_math: { ko:"%1$s 수준이에요!\n%1$s까지 모든 단원을 열어 드렸어요.\n+30 XP 🎁", en:"You're at the %1$s level!\nEverything up to %1$s is now unlocked.\n+30 XP 🎁", ja:"%1$s の レベルだよ!\n%1$s までの たんげんを ぜんぶ ひらいたよ。\n+30 XP 🎁", zh:"你的水平是%1$s!\n已解锁到%1$s的所有单元。\n+30 XP 🎁", es:"¡Estás en el nivel de %1$s!\nSe desbloqueó todo hasta %1$s.\n+30 XP 🎁", fr:"Tu es au niveau %1$s !\nTout jusqu'à %1$s est débloqué.\n+30 XP 🎁", de:"Du bist auf dem Niveau %1$s!\nAlles bis %1$s ist freigeschaltet.\n+30 XP 🎁", pt:"Você está no nível %1$s!\nTudo até %1$s foi desbloqueado.\n+30 XP 🎁", ru:"Твой уровень — %1$s!\nВсё до «%1$s» открыто.\n+30 XP 🎁", vi:"Bạn đang ở trình độ %1$s!\nĐã mở khóa mọi chuyên đề đến %1$s.\n+30 XP 🎁", th:"คุณอยู่ระดับ %1$s!\nปลดล็อกทุกหน่วยจนถึง %1$s แล้ว\n+30 XP 🎁", in:"Kamu di tingkat %1$s!\nSemua unit sampai %1$s terbuka.\n+30 XP 🎁" },

// ---------- 그림 뷰 ----------
play_reset_clock: { ko:"12시로", en:"To 12", ja:"12時に", zh:"回到12点", es:"A las 12", fr:"Sur 12", de:"Auf 12", pt:"Para 12", ru:"На 12", vi:"Về 12 giờ", th:"กลับไป 12", in:"Ke pukul 12" },
play_reset_angle: { ko:"0°로", en:"To 0°", ja:"0°に", zh:"回到0°", es:"A 0°", fr:"À 0°", de:"Auf 0°", pt:"Para 0°", ru:"На 0°", vi:"Về 0°", th:"กลับไป 0°", in:"Ke 0°" },
play_group_now: { ko:"%1$d개", en:"%1$d", ja:"%1$d", zh:"%1$d", es:"%1$d", fr:"%1$d", de:"%1$d", pt:"%1$d", ru:"%1$d", vi:"%1$d", th:"%1$d", in:"%1$d" },
play_group_left: { ko:"   (남은 것 %1$d개)", en:"   (%1$d left)", ja:"   (のこり %1$d)", zh:"   (还剩 %1$d)", es:"   (quedan %1$d)", fr:"   (%1$d restants)", de:"   (%1$d übrig)", pt:"   (restam %1$d)", ru:"   (осталось %1$d)", vi:"   (còn %1$d)", th:"   (เหลือ %1$d)", in:"   (sisa %1$d)" },
play_group_done: { ko:"   다 담았어요!", en:"   All shared out!", ja:"   ぜんぶ 入れたよ!", zh:"   全部分完了!", es:"   ¡Todo repartido!", fr:"   Tout est réparti !", de:"   Alles verteilt!", pt:"   Tudo distribuído!", ru:"   Всё разложено!", vi:"   Đã chia hết!", th:"   แบ่งครบแล้ว!", in:"   Semua sudah dibagi!" },
time_hm: { ko:"%1$d시 %2$d분", en:"%1$d:%2$02d", ja:"%1$d時 %2$d分", zh:"%1$d 点 %2$d 分", es:"%1$d:%2$02d", fr:"%1$d h %2$02d", de:"%1$d:%2$02d", pt:"%1$d:%2$02d", ru:"%1$d:%2$02d", vi:"%1$d giờ %2$d phút", th:"%1$d:%2$02d", in:"%1$d:%2$02d" },
vis_clock_hint: { ko:"바늘을 끌어서 맞춰 보세요", en:"Drag the hands to set it", ja:"はりを ドラッグして あわせよう", zh:"拖动指针来对准", es:"Arrastra las manecillas para ajustar", fr:"Fais glisser les aiguilles pour régler", de:"Zieh die Zeiger zum Einstellen", pt:"Arraste os ponteiros para acertar", ru:"Потяни стрелки, чтобы выставить", vi:"Kéo kim để chỉnh", th:"ลากเข็มเพื่อตั้งเวลา", in:"Seret jarum untuk mengatur" },
vis_painted: { ko:"칠한 칸 %1$d / %2$d", en:"Coloured %1$d / %2$d", ja:"ぬったマス %1$d / %2$d", zh:"已涂 %1$d / %2$d", es:"Coloreadas %1$d / %2$d", fr:"Coloriées %1$d / %2$d", de:"Gefärbt %1$d / %2$d", pt:"Pintadas %1$d / %2$d", ru:"Закрашено %1$d / %2$d", vi:"Đã tô %1$d / %2$d", th:"ระบายแล้ว %1$d / %2$d", in:"Diwarnai %1$d / %2$d" },
vis_paint_hint: { ko:"조각을 눌러서 색칠해요", en:"Tap the pieces to colour", ja:"ピースを おして ぬろう", zh:"点击小块涂色", es:"Toca las piezas para colorear", fr:"Touche les parts pour colorier", de:"Tippe die Teile zum Färben an", pt:"Toque nas partes para pintar", ru:"Нажимай на кусочки, чтобы закрасить", vi:"Chạm vào mảnh để tô", th:"แตะชิ้นส่วนเพื่อระบายสี", in:"Ketuk potongan untuk mewarnai" },
vis_angle_hint: { ko:"파란 손잡이를 돌려요", en:"Turn the blue handle", ja:"青い ハンドルを まわそう", zh:"转动蓝色手柄", es:"Gira el mando azul", fr:"Tourne la poignée bleue", de:"Dreh den blauen Griff", pt:"Gire o manípulo azul", ru:"Поверни синюю ручку", vi:"Xoay tay cầm xanh", th:"หมุนคันโยกสีน้ำเงิน", in:"Putar tuas biru" },
vis_ngon: { ko:"정%1$d각형", en:"Regular %1$d-gon", ja:"正%1$d角形", zh:"正%1$d边形", es:"Polígono regular de %1$d lados", fr:"Polygone régulier à %1$d côtés", de:"Regelmäßiges %1$d-Eck", pt:"Polígono regular de %1$d lados", ru:"Правильный %1$d-угольник", vi:"Đa giác đều %1$d cạnh", th:"รูป %1$d เหลี่ยมด้านเท่า", in:"Segi-%1$d beraturan" },
vis_area: { ko:"넓이 %1$s", en:"Area %1$s", ja:"めんせき %1$s", zh:"面积 %1$s", es:"Área %1$s", fr:"Aire %1$s", de:"Fläche %1$s", pt:"Área %1$s", ru:"Площадь %1$s", vi:"Diện tích %1$s", th:"พื้นที่ %1$s", in:"Luas %1$s" },
vis_total: { ko:"전체 %1$s", en:"Total %1$s", ja:"ぜんたい %1$s", zh:"总共 %1$s", es:"Total %1$s", fr:"Total %1$s", de:"Gesamt %1$s", pt:"Total %1$s", ru:"Всего %1$s", vi:"Tổng %1$s", th:"ทั้งหมด %1$s", in:"Total %1$s" },
vis_elements: { ko:"원소 %1$d개", en:"%1$d elements", ja:"ようそ %1$d こ", zh:"%1$d 个元素", es:"%1$d elementos", fr:"%1$d éléments", de:"%1$d Elemente", pt:"%1$d elementos", ru:"%1$d элементов", vi:"%1$d phần tử", th:"สมาชิก %1$d ตัว", in:"%1$d anggota" },
vis_converge: { ko:"aₙ이 점점 다가가요", en:"aₙ keeps getting closer", ja:"aₙ が だんだん ちかづくよ", zh:"aₙ 越来越接近", es:"aₙ se acerca cada vez más", fr:"aₙ s'en approche de plus en plus", de:"aₙ nähert sich immer mehr an", pt:"aₙ se aproxima cada vez mais", ru:"aₙ всё ближе и ближе", vi:"aₙ ngày càng tiến gần", th:"aₙ เข้าใกล้ขึ้นเรื่อย ๆ", in:"aₙ makin mendekat" },
basket_no: { ko:"%1$d번", en:"#%1$d", ja:"%1$d ばん", zh:"第%1$d个", es:"N.º %1$d", fr:"N° %1$d", de:"Nr. %1$d", pt:"N.º %1$d", ru:"№%1$d", vi:"Số %1$d", th:"อันที่ %1$d", in:"No. %1$d" },
balance_ok: { ko:"⚖️ 평형이에요!", en:"⚖️ Balanced!", ja:"⚖️ つりあった!", zh:"⚖️ 平衡了!", es:"⚖️ ¡Equilibrada!", fr:"⚖️ Équilibré !", de:"⚖️ Im Gleichgewicht!", pt:"⚖️ Equilibrada!", ru:"⚖️ Равновесие!", vi:"⚖️ Cân bằng!", th:"⚖️ สมดุลแล้ว!", in:"⚖️ Seimbang!" },
balance_left: { ko:"왼쪽이 더 무거워요", en:"The left side is heavier", ja:"ひだりが おもいよ", zh:"左边更重", es:"El lado izquierdo pesa más", fr:"Le côté gauche est plus lourd", de:"Die linke Seite ist schwerer", pt:"O lado esquerdo está mais pesado", ru:"Левая сторона тяжелее", vi:"Bên trái nặng hơn", th:"ด้านซ้ายหนักกว่า", in:"Sisi kiri lebih berat" },
balance_right: { ko:"오른쪽이 더 무거워요", en:"The right side is heavier", ja:"みぎが おもいよ", zh:"右边更重", es:"El lado derecho pesa más", fr:"Le côté droit est plus lourd", de:"Die rechte Seite ist schwerer", pt:"O lado direito está mais pesado", ru:"Правая сторона тяжелее", vi:"Bên phải nặng hơn", th:"ด้านขวาหนักกว่า", in:"Sisi kanan lebih berat" },
combo_streak: { ko:"🔥 %1$d연속!", en:"🔥 %1$d in a row!", ja:"🔥 %1$d れんぞく!", zh:"🔥 连续 %1$d 次!", es:"🔥 ¡%1$d seguidas!", fr:"🔥 %1$d d'affilée !", de:"🔥 %1$d in Folge!", pt:"🔥 %1$d seguidas!", ru:"🔥 %1$d подряд!", vi:"🔥 %1$d liên tiếp!", th:"🔥 ติดกัน %1$d ครั้ง!", in:"🔥 %1$d berturut-turut!" },
chick_cheer1: { ko:"힘내! 🐥", en:"You can do it! 🐥", ja:"がんばって! 🐥", zh:"加油! 🐥", es:"¡Tú puedes! 🐥", fr:"Courage ! 🐥", de:"Du schaffst das! 🐥", pt:"Você consegue! 🐥", ru:"Ты справишься! 🐥", vi:"Cố lên nhé! 🐥", th:"สู้ ๆ นะ! 🐥", in:"Kamu pasti bisa! 🐥" },
chick_cheer2: { ko:"천천히 해도 돼!", en:"Take your time!", ja:"ゆっくりで いいよ!", zh:"慢慢来也没关系!", es:"¡Tómate tu tiempo!", fr:"Prends ton temps !", de:"Lass dir Zeit!", pt:"Vá com calma!", ru:"Не спеши!", vi:"Cứ từ từ nhé!", th:"ค่อย ๆ ทำก็ได้!", in:"Santai saja!" },
chick_cheer3: { ko:"삐약! 할 수 있어!", en:"Peep! You've got this!", ja:"ピヨ! できるよ!", zh:"啾! 你可以的!", es:"¡Pío! ¡Tú puedes!", fr:"Piou ! Tu vas y arriver !", de:"Piep! Das schaffst du!", pt:"Piu! Você consegue!", ru:"Пи-пи! У тебя получится!", vi:"Chíp! Bạn làm được mà!", th:"เจี๊ยบ! ทำได้แน่นอน!", in:"Ciap! Kamu bisa!" },

// ---------- 통계 ----------
stats_counters: { ko:"📚 완료한 레슨  %1$d개\n💯 퍼펙트 레슨  %2$d개\n💊 클리어한 오답  %3$d개\n🗓 공부한 날  %4$d일", en:"📚 Lessons finished  %1$d\n💯 Perfect lessons  %2$d\n💊 Mistakes cleared  %3$d\n🗓 Days studied  %4$d", ja:"📚 おわった レッスン  %1$d\n💯 パーフェクト  %2$d\n💊 クリアした まちがい  %3$d\n🗓 べんきょうした日  %4$d", zh:"📚 完成的课程  %1$d\n💯 满分课程  %2$d\n💊 攻克的错题  %3$d\n🗓 学习天数  %4$d", es:"📚 Lecciones completadas  %1$d\n💯 Lecciones perfectas  %2$d\n💊 Errores superados  %3$d\n🗓 Días estudiados  %4$d", fr:"📚 Leçons terminées  %1$d\n💯 Leçons parfaites  %2$d\n💊 Erreurs corrigées  %3$d\n🗓 Jours étudiés  %4$d", de:"📚 Abgeschlossene Lektionen  %1$d\n💯 Perfekte Lektionen  %2$d\n💊 Erledigte Fehler  %3$d\n🗓 Lerntage  %4$d", pt:"📚 Lições concluídas  %1$d\n💯 Lições perfeitas  %2$d\n💊 Erros superados  %3$d\n🗓 Dias estudados  %4$d", ru:"📚 Пройдено уроков  %1$d\n💯 Идеальных уроков  %2$d\n💊 Закрыто ошибок  %3$d\n🗓 Дней занятий  %4$d", vi:"📚 Bài học hoàn thành  %1$d\n💯 Bài hoàn hảo  %2$d\n💊 Câu sai đã xử lý  %3$d\n🗓 Số ngày học  %4$d", th:"📚 บทที่เรียนจบ  %1$d\n💯 บทที่ได้เต็ม  %2$d\n💊 ข้อผิดที่แก้แล้ว  %3$d\n🗓 วันที่เรียน  %4$d", in:"📚 Pelajaran selesai  %1$d\n💯 Pelajaran sempurna  %2$d\n💊 Kesalahan tuntas  %3$d\n🗓 Hari belajar  %4$d" },


// ---------- 마지막 조각 ----------
result_stats: { ko:"정답률 %1$d%% · +%2$d XP", en:"%1$d%% correct · +%2$d XP", ja:"せいかいりつ %1$d%% · +%2$d XP", zh:"正确率 %1$d%% · +%2$d XP", es:"%1$d%% de acierto · +%2$d XP", fr:"%1$d%% de réussite · +%2$d XP", de:"%1$d%% richtig · +%2$d XP", pt:"%1$d%% de acerto · +%2$d XP", ru:"Точность %1$d%% · +%2$d XP", vi:"Đúng %1$d%% · +%2$d XP", th:"ถูก %1$d%% · +%2$d XP", in:"Benar %1$d%% · +%2$d XP" },
box: { ko:"상자", en:"Box", ja:"はこ", zh:"盒子", es:"Caja", fr:"Boîte", de:"Kiste", pt:"Caixa", ru:"Коробка", vi:"Hộp", th:"กล่อง", in:"Kotak" },


// ---------- 레이아웃 고정 문구 ----------
ma_listen: { ko:"🔊 듣기", en:"🔊 Listen", ja:"🔊 きく", zh:"🔊 听", es:"🔊 Escuchar", fr:"🔊 Écouter", de:"🔊 Anhören", pt:"🔊 Ouvir", ru:"🔊 Слушать", vi:"🔊 Nghe", th:"🔊 ฟัง", in:"🔊 Dengarkan" },
ma_track: { ko:"트랙", en:"Track", ja:"トラック", zh:"轨道", es:"Pista", fr:"Piste", de:"Track", pt:"Trilha", ru:"Трек", vi:"Lộ trình", th:"คอร์ส", in:"Jalur" },
ma_sfx_note: { ko:"너무 크면 문제 읽어 주는 소리가 잘 안 들려요", en:"If it's too loud, the read-aloud voice is hard to hear", ja:"おおきすぎると もんだいを よむ こえが きこえにくいよ", zh:"太大声会听不清读题的声音", es:"Si está muy alto, la voz que lee se oye mal", fr:"Trop fort, on entend mal la voix de lecture", de:"Zu laut übertönt die Vorlesestimme", pt:"Muito alto atrapalha a voz de leitura", ru:"Слишком громко — голос чтения плохо слышно", vi:"To quá sẽ khó nghe giọng đọc đề", th:"ดังเกินไปจะฟังเสียงอ่านโจทย์ไม่ชัด", in:"Terlalu keras membuat suara pembaca soal sulit terdengar" },
ma_about: { ko:"삐약수학 🐥 나만의 수학 공부 앱", en:"Peep Math 🐥 your very own math study app", ja:"ピープさんすう 🐥 じぶんだけの さんすう アプリ", zh:"啾啾数学 🐥 属于你的数学学习应用", es:"Peep Math 🐥 tu propia app de mates", fr:"Peep Math 🐥 ton appli de maths à toi", de:"Peep Math 🐥 deine eigene Mathe-App", pt:"Peep Math 🐥 seu app de matemática", ru:"Peep Math 🐥 твоё приложение для математики", vi:"Peep Math 🐥 ứng dụng toán của riêng bạn", th:"Peep Math 🐥 แอปเรียนคณิตของคุณ", in:"Peep Math 🐥 aplikasi belajar matematikamu" },


// 앱 언어 고르기 (설정) — 언어 이름 자체는 그 언어로 코드에 적는다
ly_language: { ko:"언어", en:"Language", ja:"言語", zh:"语言", es:"Idioma", fr:"Langue", de:"Sprache", pt:"Idioma", ru:"Язык", vi:"Ngôn ngữ", th:"ภาษา", in:"Bahasa" },
ly_lang_system: { ko:"기기 설정 따름", en:"System default", ja:"たんまつの せっていに したがう", zh:"跟随系统设置", es:"Predeterminado del sistema", fr:"Paramètre du système", de:"Systemstandard", pt:"Padrão do sistema", ru:"Как в системе", vi:"Theo hệ thống", th:"ตามค่าระบบ", in:"Ikuti sistem" },

};
