/**
 * 지갑·상점·부모 설정 문자열.
 *
 * 통화는 **원(₩) 그대로**다. 부모가 실제로 주는 돈이 원화이므로 달러로 바꾸면
 * 오히려 거짓말이 된다. 대신 "1,200 won" 처럼 각 언어로 읽어 준다.
 */
module.exports = {

// 용돈 단위: 한국은 "원", 그 외 나라는 통화를 못 박지 않고 동전+숫자로만 —
// 러시아 부모에게 "300 вон"은 틀린 표기다. 실제 지급 화폐는 부모가 정한다.
wallet_amount: { ko:"%1$s원", en:"🪙 %1$s", ja:"🪙 %1$s", zh:"🪙 %1$s", es:"🪙 %1$s", fr:"🪙 %1$s", de:"🪙 %1$s", pt:"🪙 %1$s", ru:"🪙 %1$s", vi:"🪙 %1$s", th:"🪙 %1$s", in:"🪙 %1$s" },
wallet_earned: { ko:"지금까지 모은 돈 %1$s", en:"Earned so far: %1$s", ja:"これまでに ためた お金 %1$s", zh:"目前攒到 %1$s", es:"Ganado hasta ahora: %1$s", fr:"Gagné jusqu'ici : %1$s", de:"Bisher verdient: %1$s", pt:"Ganho até agora: %1$s", ru:"Накоплено: %1$s", vi:"Đã kiếm được: %1$s", th:"สะสมได้แล้ว %1$s", in:"Terkumpul sejauh ini: %1$s" },
wallet_spent: { ko:"상점에서 쓴 돈 %1$s · 현금으로 받은 돈 %2$s", en:"Spent in shop: %1$s · Cashed out: %2$s", ja:"ショップで つかった %1$s · 現金で もらった %2$s", zh:"商店花费 %1$s · 已兑现 %2$s", es:"Gastado en la tienda: %1$s · Cobrado: %2$s", fr:"Dépensé en boutique : %1$s · Retiré : %2$s", de:"Im Shop ausgegeben: %1$s · Ausgezahlt: %2$s", pt:"Gasto na loja: %1$s · Sacado: %2$s", ru:"Потрачено в магазине: %1$s · Выплачено: %2$s", vi:"Đã tiêu ở cửa hàng: %1$s · Đã đổi tiền: %2$s", th:"ใช้ในร้าน %1$s · แลกเป็นเงินสด %2$s", in:"Dibelanjakan: %1$s · Dicairkan: %2$s" },
wallet_no_log: { ko:"아직 기록이 없어요. 문제를 풀어 용돈을 모아 봐요! 🐥", en:"No history yet. Solve problems to earn pocket money! 🐥", ja:"まだ きろくが ないよ。もんだいを といて おこづかいを ためよう! 🐥", zh:"还没有记录。做题来攒零花钱吧! 🐥", es:"Aún no hay historial. ¡Resuelve problemas para ganar dinero! 🐥", fr:"Pas encore d'historique. Résous des problèmes pour gagner de l'argent ! 🐥", de:"Noch kein Verlauf. Löse Aufgaben und verdiene Taschengeld! 🐥", pt:"Ainda sem histórico. Resolva problemas para ganhar mesada! 🐥", ru:"Пока нет записей. Решай задачи и копи карманные! 🐥", vi:"Chưa có lịch sử. Giải bài để kiếm tiền tiêu vặt nhé! 🐥", th:"ยังไม่มีประวัติ ทำโจทย์เพื่อสะสมเงินกันเถอะ! 🐥", in:"Belum ada riwayat. Kerjakan soal untuk dapat uang saku! 🐥" },

// ---------- 상점 묶음 ----------
shop_g_consumable: { ko:"쓰면 없어지는 것", en:"Used up when you use it", ja:"つかうと なくなる もの", zh:"用了就没了", es:"Se gasta al usarlo", fr:"Se consomme à l'usage", de:"Wird beim Benutzen verbraucht", pt:"Acaba quando usado", ru:"Расходуется при использовании", vi:"Dùng là hết", th:"ใช้แล้วหมดไป", in:"Habis saat dipakai" },
shop_g_upgrade: { ko:"영원히 남는 것", en:"Yours forever", ja:"ずっと のこる もの", zh:"永久保留", es:"Tuyo para siempre", fr:"À toi pour toujours", de:"Bleibt für immer", pt:"Seu para sempre", ru:"Остаётся навсегда", vi:"Giữ mãi mãi", th:"เก็บไว้ตลอดไป", in:"Milikmu selamanya" },
shop_g_sticker: { ko:"스티커 (홈에 자랑하기)", en:"Stickers (show off on your home screen)", ja:"シール (ホームに かざる)", zh:"贴纸 (在主页展示)", es:"Pegatinas (para lucir en el inicio)", fr:"Autocollants (à exposer sur l'accueil)", de:"Sticker (auf der Startseite zeigen)", pt:"Adesivos (mostre na tela inicial)", ru:"Наклейки (украсить главный экран)", vi:"Hình dán (khoe ở màn hình chính)", th:"สติกเกอร์ (โชว์ที่หน้าหลัก)", in:"Stiker (pamerkan di beranda)" },
shop_g_theme: { ko:"테마 (홈 배경 바꾸기)", en:"Themes (change your home background)", ja:"テーマ (ホームの はいけいを かえる)", zh:"主题 (更换主页背景)", es:"Temas (cambia el fondo del inicio)", fr:"Thèmes (change le fond d'accueil)", de:"Themes (Startseiten-Hintergrund ändern)", pt:"Temas (mude o fundo da tela inicial)", ru:"Темы (сменить фон главного экрана)", vi:"Chủ đề (đổi nền màn hình chính)", th:"ธีม (เปลี่ยนพื้นหลังหน้าหลัก)", in:"Tema (ubah latar beranda)" },

// ---------- 상품 ----------
shop_heart_refill: { ko:"하트 가득 채우기", en:"Refill all hearts", ja:"ハートを ぜんぶ かいふく", zh:"补满爱心", es:"Rellenar corazones", fr:"Recharger les cœurs", de:"Herzen auffüllen", pt:"Encher os corações", ru:"Восполнить сердечки", vi:"Hồi đầy tim", th:"เติมหัวใจเต็ม", in:"Isi penuh hati" },
shop_heart_refill_d: { ko:"하트를 최대치까지 즉시 회복해요", en:"Instantly restores hearts to the maximum", ja:"ハートを さいだいまで すぐに かいふくするよ", zh:"立刻把爱心恢复到上限", es:"Restaura al instante los corazones al máximo", fr:"Restaure aussitôt les cœurs au maximum", de:"Füllt die Herzen sofort bis zum Maximum", pt:"Restaura os corações ao máximo na hora", ru:"Мгновенно восполняет сердечки до максимума", vi:"Hồi tim đầy ngay lập tức", th:"เติมหัวใจจนเต็มทันที", in:"Langsung memulihkan hati ke maksimum" },
shop_hint3: { ko:"힌트권 3개", en:"3 hint tickets", ja:"ヒント券 3まい", zh:"3 张提示券", es:"3 pistas", fr:"3 indices", de:"3 Tipp-Tickets", pt:"3 dicas", ru:"3 подсказки", vi:"3 vé gợi ý", th:"บัตรคำใบ้ 3 ใบ", in:"3 tiket petunjuk" },
shop_hint3_d: { ko:"4지선다에서 오답 2개를 지워 줘요", en:"Removes 2 wrong choices on multiple-choice questions", ja:"4たくで まちがいを 2つ けしてくれる", zh:"在四选一题中划掉2个错误答案", es:"Elimina 2 opciones incorrectas", fr:"Élimine 2 mauvaises réponses", de:"Streicht 2 falsche Antworten", pt:"Remove 2 opções erradas", ru:"Убирает 2 неверных варианта", vi:"Xóa 2 đáp án sai", th:"ตัดตัวเลือกผิดออก 2 ข้อ", in:"Menghapus 2 pilihan salah" },
shop_heart_up: { ko:"하트 최대치 +1", en:"Max hearts +1", ja:"ハートの さいだい +1", zh:"爱心上限 +1", es:"Corazones máximos +1", fr:"Cœurs max +1", de:"Max. Herzen +1", pt:"Corações máx. +1", ru:"Максимум сердечек +1", vi:"Tim tối đa +1", th:"หัวใจสูงสุด +1", in:"Hati maksimum +1" },
shop_heart_up_d: { ko:"하트를 한 개 더 가질 수 있어요 (최대 8개)", en:"Hold one more heart (up to 8)", ja:"ハートを 1つ おおく もてる (さいだい 8こ)", zh:"可以多拥有1颗爱心 (最多8颗)", es:"Puedes tener un corazón más (hasta 8)", fr:"Un cœur de plus (jusqu'à 8)", de:"Ein Herz mehr (bis zu 8)", pt:"Tenha mais um coração (até 8)", ru:"Ещё одно сердечко (до 8)", vi:"Có thêm một tim (tối đa 8)", th:"มีหัวใจเพิ่มอีก 1 ดวง (สูงสุด 8)", in:"Punya satu hati lagi (maks 8)" },
shop_sticker_d: { ko:"홈 화면에 붙일 수 있어요", en:"Stick it on your home screen", ja:"ホームがめんに はれるよ", zh:"可以贴在主页上", es:"Puedes pegarla en el inicio", fr:"À coller sur l'accueil", de:"Kann auf die Startseite geklebt werden", pt:"Cole na sua tela inicial", ru:"Можно приклеить на главный экран", vi:"Có thể dán lên màn hình chính", th:"ติดที่หน้าหลักได้", in:"Bisa ditempel di beranda" },
shop_st_star: { ko:"반짝 별 스티커", en:"Sparkle star sticker", ja:"きらきら星 シール", zh:"闪亮星星贴纸", es:"Pegatina de estrella brillante", fr:"Autocollant étoile brillante", de:"Funkelstern-Sticker", pt:"Adesivo de estrela brilhante", ru:"Наклейка «Звёздочка»", vi:"Hình dán ngôi sao lấp lánh", th:"สติกเกอร์ดาวประกาย", in:"Stiker bintang berkilau" },
shop_st_rocket: { ko:"로켓 스티커", en:"Rocket sticker", ja:"ロケット シール", zh:"火箭贴纸", es:"Pegatina de cohete", fr:"Autocollant fusée", de:"Raketen-Sticker", pt:"Adesivo de foguete", ru:"Наклейка «Ракета»", vi:"Hình dán tên lửa", th:"สติกเกอร์จรวด", in:"Stiker roket" },
shop_st_crown: { ko:"왕관 스티커", en:"Crown sticker", ja:"おうかん シール", zh:"皇冠贴纸", es:"Pegatina de corona", fr:"Autocollant couronne", de:"Kronen-Sticker", pt:"Adesivo de coroa", ru:"Наклейка «Корона»", vi:"Hình dán vương miện", th:"สติกเกอร์มงกุฎ", in:"Stiker mahkota" },
shop_st_rainbow: { ko:"무지개 스티커", en:"Rainbow sticker", ja:"にじ シール", zh:"彩虹贴纸", es:"Pegatina de arcoíris", fr:"Autocollant arc-en-ciel", de:"Regenbogen-Sticker", pt:"Adesivo de arco-íris", ru:"Наклейка «Радуга»", vi:"Hình dán cầu vồng", th:"สติกเกอร์สายรุ้ง", in:"Stiker pelangi" },
shop_st_dino: { ko:"공룡 스티커", en:"Dinosaur sticker", ja:"きょうりゅう シール", zh:"恐龙贴纸", es:"Pegatina de dinosaurio", fr:"Autocollant dinosaure", de:"Dino-Sticker", pt:"Adesivo de dinossauro", ru:"Наклейка «Динозавр»", vi:"Hình dán khủng long", th:"สติกเกอร์ไดโนเสาร์", in:"Stiker dinosaurus" },
shop_st_cake: { ko:"케이크 스티커", en:"Cake sticker", ja:"ケーキ シール", zh:"蛋糕贴纸", es:"Pegatina de pastel", fr:"Autocollant gâteau", de:"Kuchen-Sticker", pt:"Adesivo de bolo", ru:"Наклейка «Торт»", vi:"Hình dán bánh kem", th:"สติกเกอร์เค้ก", in:"Stiker kue" },
shop_st_medal: { ko:"금메달 스티커", en:"Gold medal sticker", ja:"きんメダル シール", zh:"金牌贴纸", es:"Pegatina de medalla de oro", fr:"Autocollant médaille d'or", de:"Goldmedaillen-Sticker", pt:"Adesivo de medalha de ouro", ru:"Наклейка «Золотая медаль»", vi:"Hình dán huy chương vàng", th:"สติกเกอร์เหรียญทอง", in:"Stiker medali emas" },
shop_st_unicorn: { ko:"유니콘 스티커", en:"Unicorn sticker", ja:"ユニコーン シール", zh:"独角兽贴纸", es:"Pegatina de unicornio", fr:"Autocollant licorne", de:"Einhorn-Sticker", pt:"Adesivo de unicórnio", ru:"Наклейка «Единорог»", vi:"Hình dán kỳ lân", th:"สติกเกอร์ยูนิคอร์น", in:"Stiker unicorn" },
shop_th_sky: { ko:"하늘 테마", en:"Sky theme", ja:"そら テーマ", zh:"天空主题", es:"Tema cielo", fr:"Thème ciel", de:"Himmel-Theme", pt:"Tema céu", ru:"Тема «Небо»", vi:"Chủ đề bầu trời", th:"ธีมท้องฟ้า", in:"Tema langit" },
shop_th_sky_d: { ko:"홈 배경이 하늘색이 돼요", en:"Turns your home background sky blue", ja:"ホームの はいけいが そらいろに なるよ", zh:"把主页背景变成天蓝色", es:"Pone el fondo del inicio azul cielo", fr:"Met le fond d'accueil en bleu ciel", de:"Färbt den Hintergrund himmelblau", pt:"Deixa o fundo azul-céu", ru:"Делает фон небесно-голубым", vi:"Đổi nền thành màu xanh trời", th:"เปลี่ยนพื้นหลังเป็นสีฟ้า", in:"Mengubah latar jadi biru langit" },
shop_th_mint: { ko:"민트 테마", en:"Mint theme", ja:"ミント テーマ", zh:"薄荷主题", es:"Tema menta", fr:"Thème menthe", de:"Minz-Theme", pt:"Tema menta", ru:"Тема «Мята»", vi:"Chủ đề bạc hà", th:"ธีมมิ้นต์", in:"Tema mint" },
shop_th_mint_d: { ko:"홈 배경이 민트색이 돼요", en:"Turns your home background mint", ja:"ホームの はいけいが ミントいろに なるよ", zh:"把主页背景变成薄荷色", es:"Pone el fondo del inicio color menta", fr:"Met le fond d'accueil en menthe", de:"Färbt den Hintergrund mintgrün", pt:"Deixa o fundo cor de menta", ru:"Делает фон мятным", vi:"Đổi nền thành màu bạc hà", th:"เปลี่ยนพื้นหลังเป็นสีมิ้นต์", in:"Mengubah latar jadi mint" },
shop_th_pink: { ko:"벚꽃 테마", en:"Blossom theme", ja:"さくら テーマ", zh:"樱花主题", es:"Tema flor de cerezo", fr:"Thème fleur de cerisier", de:"Kirschblüten-Theme", pt:"Tema flor de cerejeira", ru:"Тема «Сакура»", vi:"Chủ đề hoa anh đào", th:"ธีมซากุระ", in:"Tema bunga sakura" },
shop_th_pink_d: { ko:"홈 배경이 분홍색이 돼요", en:"Turns your home background pink", ja:"ホームの はいけいが ピンクに なるよ", zh:"把主页背景变成粉色", es:"Pone el fondo del inicio rosa", fr:"Met le fond d'accueil en rose", de:"Färbt den Hintergrund rosa", pt:"Deixa o fundo rosa", ru:"Делает фон розовым", vi:"Đổi nền thành màu hồng", th:"เปลี่ยนพื้นหลังเป็นสีชมพู", in:"Mengubah latar jadi merah muda" },
shop_th_lav: { ko:"라벤더 테마", en:"Lavender theme", ja:"ラベンダー テーマ", zh:"薰衣草主题", es:"Tema lavanda", fr:"Thème lavande", de:"Lavendel-Theme", pt:"Tema lavanda", ru:"Тема «Лаванда»", vi:"Chủ đề oải hương", th:"ธีมลาเวนเดอร์", in:"Tema lavender" },
shop_th_lav_d: { ko:"홈 배경이 보라색이 돼요", en:"Turns your home background purple", ja:"ホームの はいけいが むらさきに なるよ", zh:"把主页背景变成紫色", es:"Pone el fondo del inicio morado", fr:"Met le fond d'accueil en violet", de:"Färbt den Hintergrund lila", pt:"Deixa o fundo roxo", ru:"Делает фон фиолетовым", vi:"Đổi nền thành màu tím", th:"เปลี่ยนพื้นหลังเป็นสีม่วง", in:"Mengubah latar jadi ungu" },

// ---------- 구매 흐름 ----------
shop_hint_have: { ko:"%1$s  (가진 힌트권 %2$d개)", en:"%1$s  (you have %2$d)", ja:"%1$s  (もっている ヒント券 %2$d まい)", zh:"%1$s  (现有 %2$d 张)", es:"%1$s  (tienes %2$d)", fr:"%1$s  (tu en as %2$d)", de:"%1$s  (du hast %2$d)", pt:"%1$s  (você tem %2$d)", ru:"%1$s  (у тебя %2$d)", vi:"%1$s  (bạn có %2$d)", th:"%1$s  (มีอยู่ %2$d ใบ)", in:"%1$s  (kamu punya %2$d)" },
shop_heart_have: { ko:"%1$s  (현재 최대 %2$d개)", en:"%1$s  (max is %2$d now)", ja:"%1$s  (いまの さいだい %2$d こ)", zh:"%1$s  (当前上限 %2$d)", es:"%1$s  (máximo actual %2$d)", fr:"%1$s  (max actuel %2$d)", de:"%1$s  (aktuelles Maximum %2$d)", pt:"%1$s  (máximo atual %2$d)", ru:"%1$s  (сейчас максимум %2$d)", vi:"%1$s  (tối đa hiện tại %2$d)", th:"%1$s  (สูงสุดตอนนี้ %2$d)", in:"%1$s  (maksimum saat ini %2$d)" },
shop_maxed: { ko:"최대", en:"Maxed", ja:"さいだい", zh:"已满", es:"Al máximo", fr:"Au max", de:"Maximal", pt:"No máximo", ru:"Максимум", vi:"Tối đa", th:"สูงสุดแล้ว", in:"Maksimum" },
shop_in_use: { ko:"사용 중", en:"In use", ja:"つかっている", zh:"使用中", es:"En uso", fr:"Utilisé", de:"In Gebrauch", pt:"Em uso", ru:"Используется", vi:"Đang dùng", th:"กำลังใช้", in:"Dipakai" },
shop_apply: { ko:"적용", en:"Apply", ja:"てきよう", zh:"应用", es:"Aplicar", fr:"Appliquer", de:"Anwenden", pt:"Aplicar", ru:"Применить", vi:"Áp dụng", th:"ใช้", in:"Terapkan" },
shop_not_enough: { ko:"용돈이 %1$s 모자라요. 문제를 더 풀어 봐요! 🐥", en:"You're %1$s short. Solve more problems! 🐥", ja:"おこづかいが %1$s たりないよ。もっと といてみよう! 🐥", zh:"还差 %1$s。再多做几题吧! 🐥", es:"Te faltan %1$s. ¡Resuelve más problemas! 🐥", fr:"Il te manque %1$s. Résous plus de problèmes ! 🐥", de:"Dir fehlen %1$s. Löse mehr Aufgaben! 🐥", pt:"Faltam %1$s. Resolva mais problemas! 🐥", ru:"Не хватает %1$s. Реши ещё задач! 🐥", vi:"Còn thiếu %1$s. Giải thêm bài nhé! 🐥", th:"ยังขาดอีก %1$s ทำโจทย์เพิ่มอีกนะ! 🐥", in:"Kurang %1$s. Kerjakan soal lagi! 🐥" },
shop_buy_ask: { ko:"%1$s\n\n%2$s을 쓸까요?\n(남는 돈 %3$s)", en:"%1$s\n\nSpend %2$s?\n(%3$s left)", ja:"%1$s\n\n%2$s つかう?\n(のこり %3$s)", zh:"%1$s\n\n要花 %2$s 吗?\n(剩余 %3$s)", es:"%1$s\n\n¿Gastar %2$s?\n(quedan %3$s)", fr:"%1$s\n\nDépenser %2$s ?\n(reste %3$s)", de:"%1$s\n\n%2$s ausgeben?\n(%3$s bleiben)", pt:"%1$s\n\nGastar %2$s?\n(restam %3$s)", ru:"%1$s\n\nПотратить %2$s?\n(останется %3$s)", vi:"%1$s\n\nDùng %2$s nhé?\n(còn lại %3$s)", th:"%1$s\n\nใช้ %2$s ไหม?\n(เหลือ %3$s)", in:"%1$s\n\nPakai %2$s?\n(sisa %3$s)" },
shop_buy_yes: { ko:"살래요", en:"Buy it", ja:"かう", zh:"买", es:"Comprar", fr:"Acheter", de:"Kaufen", pt:"Comprar", ru:"Купить", vi:"Mua", th:"ซื้อ", in:"Beli" },
shop_buy_later: { ko:"다음에", en:"Maybe later", ja:"またこんど", zh:"下次吧", es:"Luego", fr:"Plus tard", de:"Später", pt:"Depois", ru:"Позже", vi:"Để sau", th:"ไว้ก่อน", in:"Nanti saja" },
shop_heart_full: { ko:"하트가 가득 찼어요! ❤️ %1$d", en:"Hearts are full! ❤️ %1$d", ja:"ハートが まんタンだよ! ❤️ %1$d", zh:"爱心满了! ❤️ %1$d", es:"¡Corazones llenos! ❤️ %1$d", fr:"Cœurs au maximum ! ❤️ %1$d", de:"Herzen voll! ❤️ %1$d", pt:"Corações cheios! ❤️ %1$d", ru:"Сердечки полны! ❤️ %1$d", vi:"Tim đã đầy! ❤️ %1$d", th:"หัวใจเต็มแล้ว! ❤️ %1$d", in:"Hati penuh! ❤️ %1$d" },
shop_got_hints: { ko:"힌트권 %1$d개를 받았어요! 💡", en:"You got %1$d hint tickets! 💡", ja:"ヒント券を %1$d まい もらったよ! 💡", zh:"获得了 %1$d 张提示券! 💡", es:"¡Conseguiste %1$d pistas! 💡", fr:"Tu as reçu %1$d indices ! 💡", de:"Du hast %1$d Tipp-Tickets bekommen! 💡", pt:"Você ganhou %1$d dicas! 💡", ru:"Получено подсказок: %1$d! 💡", vi:"Bạn nhận được %1$d vé gợi ý! 💡", th:"ได้รับบัตรคำใบ้ %1$d ใบ! 💡", in:"Kamu dapat %1$d tiket petunjuk! 💡" },
shop_heart_up_done: { ko:"이제 하트를 %1$d개까지 가질 수 있어요! ❤️‍🔥", en:"You can now hold up to %1$d hearts! ❤️‍🔥", ja:"これで ハートを %1$d こまで もてるよ! ❤️‍🔥", zh:"现在最多可以有 %1$d 颗爱心! ❤️‍🔥", es:"¡Ahora puedes tener hasta %1$d corazones! ❤️‍🔥", fr:"Tu peux maintenant avoir %1$d cœurs ! ❤️‍🔥", de:"Jetzt kannst du bis zu %1$d Herzen haben! ❤️‍🔥", pt:"Agora você pode ter até %1$d corações! ❤️‍🔥", ru:"Теперь можно иметь до %1$d сердечек! ❤️‍🔥", vi:"Giờ bạn có thể giữ tới %1$d tim! ❤️‍🔥", th:"ตอนนี้มีหัวใจได้ถึง %1$d ดวง! ❤️‍🔥", in:"Sekarang kamu bisa punya %1$d hati! ❤️‍🔥" },
shop_sticker_on: { ko:"%1$s 스티커를 붙였어요!", en:"Stuck the %1$s sticker on!", ja:"%1$s シールを はったよ!", zh:"贴上了 %1$s 贴纸!", es:"¡Pegaste la pegatina %1$s!", fr:"Autocollant %1$s collé !", de:"%1$s-Sticker aufgeklebt!", pt:"Colou o adesivo %1$s!", ru:"Наклейка %1$s приклеена!", vi:"Đã dán hình %1$s!", th:"ติดสติกเกอร์ %1$s แล้ว!", in:"Stiker %1$s ditempel!" },
shop_theme_on: { ko:"%1$s로 바꿨어요! %2$s", en:"Switched to %1$s! %2$s", ja:"%1$s に かえたよ! %2$s", zh:"已切换到%1$s! %2$s", es:"¡Cambiado a %1$s! %2$s", fr:"Passé au %1$s ! %2$s", de:"Zu %1$s gewechselt! %2$s", pt:"Mudou para %1$s! %2$s", ru:"Переключено на %1$s! %2$s", vi:"Đã đổi sang %1$s! %2$s", th:"เปลี่ยนเป็น%1$s แล้ว! %2$s", in:"Beralih ke %1$s! %2$s" },
shop_applied: { ko:"%1$s 적용!", en:"%1$s applied!", ja:"%1$s てきよう!", zh:"已应用%1$s!", es:"¡%1$s aplicado!", fr:"%1$s appliqué !", de:"%1$s angewendet!", pt:"%1$s aplicado!", ru:"%1$s применено!", vi:"Đã áp dụng %1$s!", th:"ใช้%1$s แล้ว!", in:"%1$s diterapkan!" },

// ---------- 현금 지급 ----------
pay_no_money: { ko:"아직 바꿀 용돈이 없어요 🐣", en:"No pocket money to cash out yet 🐣", ja:"まだ かえる おこづかいが ないよ 🐣", zh:"还没有可兑现的零花钱 🐣", es:"Aún no hay dinero para cobrar 🐣", fr:"Pas encore d'argent à retirer 🐣", de:"Noch kein Taschengeld zum Auszahlen 🐣", pt:"Ainda não há mesada para sacar 🐣", ru:"Пока нечего обналичивать 🐣", vi:"Chưa có tiền để đổi 🐣", th:"ยังไม่มีเงินให้แลก 🐣", in:"Belum ada uang untuk dicairkan 🐣" },
pay_all: { ko:"전액 %1$s", en:"All of it (%1$s)", ja:"ぜんがく %1$s", zh:"全部 %1$s", es:"Todo (%1$s)", fr:"Tout (%1$s)", de:"Alles (%1$s)", pt:"Tudo (%1$s)", ru:"Всё (%1$s)", vi:"Toàn bộ (%1$s)", th:"ทั้งหมด (%1$s)", in:"Semuanya (%1$s)" },
pay_custom: { ko:"직접 입력", en:"Enter an amount", ja:"じぶんで 入力", zh:"手动输入", es:"Escribir cantidad", fr:"Saisir un montant", de:"Betrag eingeben", pt:"Digitar valor", ru:"Ввести сумму", vi:"Tự nhập", th:"กรอกเอง", in:"Masukkan jumlah" },
pay_how_much: { ko:"얼마를 드릴까요? (최대 %1$d)", en:"How much? (up to %1$d)", ja:"いくら わたす? (さいだい %1$d)", zh:"要给多少? (最多 %1$d)", es:"¿Cuánto? (hasta %1$d)", fr:"Combien ? (jusqu'à %1$d)", de:"Wie viel? (bis %1$d)", pt:"Quanto? (até %1$d)", ru:"Сколько? (до %1$d)", vi:"Bao nhiêu? (tối đa %1$d)", th:"เท่าไร? (ไม่เกิน %1$d)", in:"Berapa? (maks %1$d)" },
pay_enter_amount: { ko:"금액 입력", en:"Enter amount", ja:"きんがく 入力", zh:"输入金额", es:"Introducir cantidad", fr:"Saisir le montant", de:"Betrag eingeben", pt:"Digite o valor", ru:"Введите сумму", vi:"Nhập số tiền", th:"กรอกจำนวนเงิน", in:"Masukkan jumlah" },
pay_bad_amount: { ko:"금액을 다시 확인해 주세요", en:"Please check the amount again", ja:"きんがくを もういちど かくにんしてね", zh:"请再确认一下金额", es:"Revisa la cantidad otra vez", fr:"Vérifie le montant", de:"Bitte den Betrag prüfen", pt:"Confira o valor de novo", ru:"Проверьте сумму ещё раз", vi:"Hãy kiểm tra lại số tiền", th:"กรุณาตรวจสอบจำนวนเงินอีกครั้ง", in:"Periksa lagi jumlahnya" },
pay_log: { ko:"현금으로 받음", en:"Cashed out", ja:"現金で うけとった", zh:"已兑现", es:"Cobrado en efectivo", fr:"Retiré en espèces", de:"Bar ausgezahlt", pt:"Recebido em dinheiro", ru:"Получено наличными", vi:"Đã nhận tiền mặt", th:"รับเป็นเงินสดแล้ว", in:"Diterima tunai" },
pay_done_title: { ko:"🎉 %1$s 지급 완료!", en:"🎉 %1$s paid out!", ja:"🎉 %1$s わたしたよ!", zh:"🎉 已支付 %1$s!", es:"🎉 ¡%1$s entregado!", fr:"🎉 %1$s versé !", de:"🎉 %1$s ausgezahlt!", pt:"🎉 %1$s pago!", ru:"🎉 Выплачено %1$s!", vi:"🎉 Đã trả %1$s!", th:"🎉 จ่าย %1$s แล้ว!", in:"🎉 %1$s sudah dibayar!" },
pay_done_msg: { ko:"부모님이 %1$s을 현금으로 주셨어요.\n남은 용돈: %2$s\n\n열심히 공부한 보람이 있네요! 🐥", en:"Your parent gave you %1$s in cash.\nRemaining: %2$s\n\nAll that studying paid off! 🐥", ja:"おうちの人が %1$s を 現金で くれたよ。\nのこり: %2$s\n\nがんばった かいが あったね! 🐥", zh:"爸爸妈妈给了你 %1$s 现金。\n剩余: %2$s\n\n努力学习有回报啦! 🐥", es:"Tu familia te dio %1$s en efectivo.\nQueda: %2$s\n\n¡Estudiar valió la pena! 🐥", fr:"Tes parents t'ont donné %1$s en espèces.\nReste : %2$s\n\nTes efforts ont payé ! 🐥", de:"Deine Eltern haben dir %1$s bar gegeben.\nRest: %2$s\n\nDas Lernen hat sich gelohnt! 🐥", pt:"Seus pais te deram %1$s em dinheiro.\nRestam: %2$s\n\nTanto estudo valeu a pena! 🐥", ru:"Родители дали тебе %1$s наличными.\nОсталось: %2$s\n\nСтарания окупились! 🐥", vi:"Bố mẹ đã đưa bạn %1$s tiền mặt.\nCòn lại: %2$s\n\nCông học tập được đền đáp rồi! 🐥", th:"พ่อแม่ให้เงินสด %1$s แล้ว\nเหลือ: %2$s\n\nความตั้งใจเรียนได้ผลแล้ว! 🐥", in:"Orang tuamu memberi %1$s tunai.\nSisa: %2$s\n\nBelajar keras terbayar! 🐥" },
pay_confirm_title: { ko:"부모님 확인", en:"Parent confirmation", ja:"おうちの人 かくにん", zh:"家长确认", es:"Confirmación de un adulto", fr:"Confirmation d'un parent", de:"Bestätigung der Eltern", pt:"Confirmação dos pais", ru:"Подтверждение родителя", vi:"Xác nhận của phụ huynh", th:"ยืนยันโดยผู้ปกครอง", in:"Konfirmasi orang tua" },
pay_confirm_msg: { ko:"%1$s을 현금으로 주시겠어요?\n확인을 누르면 지갑에서 빠지고 기록에 남아요.\n\n(설정에서 비밀번호를 걸면 아이가 혼자 누를 수 없어요)", en:"Hand over %1$s in cash?\nTapping OK removes it from the wallet and logs it.\n\n(Set a PIN in Settings so your child can't do this alone.)", ja:"%1$s を 現金で わたしますか?\nOK を おすと さいふから ひかれて きろくに のこります。\n\n(せっていで あんしょうばんごうを かけると 子どもだけでは おせません)", zh:"要给 %1$s 现金吗?\n点击确认后会从钱包扣除并留下记录。\n\n(在设置里加密码，孩子就不能自己操作了)", es:"¿Entregar %1$s en efectivo?\nAl aceptar se descuenta de la cartera y queda registrado.\n\n(Pon un PIN en Ajustes para que tu hijo no pueda hacerlo solo.)", fr:"Donner %1$s en espèces ?\nEn confirmant, la somme est retirée du portefeuille et enregistrée.\n\n(Définis un code dans les Réglages pour que l'enfant ne puisse pas le faire seul.)", de:"%1$s in bar auszahlen?\nMit OK wird der Betrag abgezogen und protokolliert.\n\n(Setze in den Einstellungen eine PIN, damit dein Kind das nicht allein kann.)", pt:"Entregar %1$s em dinheiro?\nAo confirmar, sai da carteira e fica registrado.\n\n(Defina um PIN nas Configurações para a criança não fazer sozinha.)", ru:"Выдать %1$s наличными?\nПосле подтверждения сумма спишется и попадёт в журнал.\n\n(Задайте PIN в настройках, чтобы ребёнок не сделал это сам.)", vi:"Đưa %1$s tiền mặt nhé?\nNhấn OK sẽ trừ khỏi ví và ghi vào lịch sử.\n\n(Đặt mã PIN trong Cài đặt để trẻ không tự bấm được.)", th:"จะให้เงินสด %1$s ไหม?\nกดตกลงแล้วจะถูกหักจากกระเป๋าและบันทึกไว้\n\n(ตั้งรหัสในการตั้งค่าเพื่อไม่ให้เด็กกดเอง)", in:"Berikan %1$s tunai?\nMenekan OK akan mengurangi dompet dan tercatat.\n\n(Atur PIN di Pengaturan agar anak tidak bisa sendiri.)" },
pay_gave: { ko:"현금 줬어요", en:"I gave the cash", ja:"現金 わたした", zh:"已给现金", es:"Ya di el dinero", fr:"J'ai donné l'argent", de:"Bar gegeben", pt:"Dei o dinheiro", ru:"Деньги отданы", vi:"Đã đưa tiền", th:"ให้เงินแล้ว", in:"Sudah diberikan" },
ok_nice: { ko:"좋아요!", en:"Nice!", ja:"いいね!", zh:"好耶!", es:"¡Genial!", fr:"Super !", de:"Super!", pt:"Legal!", ru:"Отлично!", vi:"Tuyệt!", th:"เยี่ยม!", in:"Asyik!" },

// ---------- 부모 비밀번호 ----------
pin_ask: { ko:"부모님 비밀번호를 넣어 주세요", en:"Enter the parent PIN", ja:"おうちの人の あんしょうばんごうを 入れてね", zh:"请输入家长密码", es:"Introduce el PIN del adulto", fr:"Saisis le code parent", de:"Eltern-PIN eingeben", pt:"Digite o PIN dos pais", ru:"Введите родительский PIN", vi:"Nhập mã PIN của phụ huynh", th:"กรอกรหัสผู้ปกครอง", in:"Masukkan PIN orang tua" },
pin_current: { ko:"지금 비밀번호", en:"Current PIN", ja:"いまの あんしょうばんごう", zh:"当前密码", es:"PIN actual", fr:"Code actuel", de:"Aktuelle PIN", pt:"PIN atual", ru:"Текущий PIN", vi:"Mã PIN hiện tại", th:"รหัสปัจจุบัน", in:"PIN saat ini" },
pin_new: { ko:"새 비밀번호", en:"New PIN", ja:"あたらしい あんしょうばんごう", zh:"新密码", es:"PIN nuevo", fr:"Nouveau code", de:"Neue PIN", pt:"Novo PIN", ru:"Новый PIN", vi:"Mã PIN mới", th:"รหัสใหม่", in:"PIN baru" },
pin_hint: { ko:"숫자 4자리", en:"4 digits", ja:"すうじ 4けた", zh:"4位数字", es:"4 dígitos", fr:"4 chiffres", de:"4 Ziffern", pt:"4 dígitos", ru:"4 цифры", vi:"4 chữ số", th:"ตัวเลข 4 หลัก", in:"4 angka" },
pin_need4: { ko:"숫자 4자리로 만들어 주세요", en:"Please use 4 digits", ja:"すうじ 4けたに してね", zh:"请使用4位数字", es:"Usa 4 dígitos, por favor", fr:"Utilise 4 chiffres", de:"Bitte 4 Ziffern verwenden", pt:"Use 4 dígitos, por favor", ru:"Введите 4 цифры", vi:"Hãy dùng 4 chữ số", th:"กรุณาใช้ตัวเลข 4 หลัก", in:"Gunakan 4 angka" },
pin_saved: { ko:"비밀번호를 저장했어요 🔒", en:"PIN saved 🔒", ja:"あんしょうばんごうを ほぞんしたよ 🔒", zh:"密码已保存 🔒", es:"PIN guardado 🔒", fr:"Code enregistré 🔒", de:"PIN gespeichert 🔒", pt:"PIN salvo 🔒", ru:"PIN сохранён 🔒", vi:"Đã lưu mã PIN 🔒", th:"บันทึกรหัสแล้ว 🔒", in:"PIN tersimpan 🔒" },
pin_removed: { ko:"비밀번호를 없앴어요", en:"PIN removed", ja:"あんしょうばんごうを けしたよ", zh:"密码已删除", es:"PIN eliminado", fr:"Code supprimé", de:"PIN entfernt", pt:"PIN removido", ru:"PIN удалён", vi:"Đã xóa mã PIN", th:"ลบรหัสแล้ว", in:"PIN dihapus" },
pin_wrong: { ko:"비밀번호가 달라요", en:"Wrong PIN", ja:"あんしょうばんごうが ちがうよ", zh:"密码不对", es:"PIN incorrecto", fr:"Code incorrect", de:"Falsche PIN", pt:"PIN incorreto", ru:"Неверный PIN", vi:"Sai mã PIN", th:"รหัสไม่ถูกต้อง", in:"PIN salah" },
pin_change: { ko:"비밀번호 바꾸기", en:"Change PIN", ja:"あんしょうばんごうを かえる", zh:"修改密码", es:"Cambiar PIN", fr:"Changer le code", de:"PIN ändern", pt:"Mudar PIN", ru:"Изменить PIN", vi:"Đổi mã PIN", th:"เปลี่ยนรหัส", in:"Ubah PIN" },
pin_remove: { ko:"비밀번호 없애기", en:"Remove PIN", ja:"あんしょうばんごうを けす", zh:"删除密码", es:"Quitar PIN", fr:"Supprimer le code", de:"PIN entfernen", pt:"Remover PIN", ru:"Удалить PIN", vi:"Xóa mã PIN", th:"ลบรหัส", in:"Hapus PIN" },
pin_create: { ko:"비밀번호 만들기 (현금 지급 잠금)", en:"Set a PIN (locks cash payouts)", ja:"あんしょうばんごうを つくる (現金しはらいを ロック)", zh:"设置密码 (锁定现金支付)", es:"Crear PIN (bloquea los pagos)", fr:"Créer un code (verrouille les retraits)", de:"PIN einrichten (sperrt Auszahlungen)", pt:"Criar PIN (bloqueia os saques)", ru:"Задать PIN (блокирует выплаты)", vi:"Tạo mã PIN (khóa việc trả tiền)", th:"ตั้งรหัส (ล็อกการจ่ายเงินสด)", in:"Buat PIN (mengunci pencairan)" },

// ---------- 공용 ----------
confirm: { ko:"확인", en:"OK", ja:"OK", zh:"确定", es:"Aceptar", fr:"OK", de:"OK", pt:"OK", ru:"OK", vi:"Đồng ý", th:"ตกลง", in:"OK" },
close: { ko:"닫기", en:"Close", ja:"とじる", zh:"关闭", es:"Cerrar", fr:"Fermer", de:"Schließen", pt:"Fechar", ru:"Закрыть", vi:"Đóng", th:"ปิด", in:"Tutup" },
save: { ko:"저장", en:"Save", ja:"ほぞん", zh:"保存", es:"Guardar", fr:"Enregistrer", de:"Speichern", pt:"Salvar", ru:"Сохранить", vi:"Lưu", th:"บันทึก", in:"Simpan" },
copy: { ko:"복사", en:"Copy", ja:"コピー", zh:"复制", es:"Copiar", fr:"Copier", de:"Kopieren", pt:"Copiar", ru:"Копировать", vi:"Sao chép", th:"คัดลอก", in:"Salin" },
crash_title: { ko:"마지막 오류 기록", en:"Last error log", ja:"さいごの エラー きろく", zh:"最近的错误记录", es:"Último registro de error", fr:"Dernier journal d'erreur", de:"Letztes Fehlerprotokoll", pt:"Último registro de erro", ru:"Последний журнал ошибок", vi:"Nhật ký lỗi gần nhất", th:"บันทึกข้อผิดพลาดล่าสุด", in:"Log kesalahan terakhir" },
goal_set_title: { ko:"🎯 오늘의 목표 정하기", en:"🎯 Set today's goal", ja:"🎯 きょうの もくひょうを きめる", zh:"🎯 设定今天的目标", es:"🎯 Fija la meta de hoy", fr:"🎯 Fixe l'objectif du jour", de:"🎯 Tagesziel festlegen", pt:"🎯 Defina a meta de hoje", ru:"🎯 Задай цель на сегодня", vi:"🎯 Đặt mục tiêu hôm nay", th:"🎯 ตั้งเป้าหมายวันนี้", in:"🎯 Tetapkan target hari ini" },
placement_level: { ko:"레벨 %1$d", en:"Level %1$d", ja:"レベル %1$d", zh:"等级 %1$d", es:"Nivel %1$d", fr:"Niveau %1$d", de:"Stufe %1$d", pt:"Nível %1$d", ru:"Уровень %1$d", vi:"Cấp %1$d", th:"ระดับ %1$d", in:"Level %1$d" },

// ---------- 통계 ----------
stats_level_big: { ko:"⭐ Lv.%1$d", en:"⭐ Lv.%1$d", ja:"⭐ Lv.%1$d", zh:"⭐ Lv.%1$d", es:"⭐ Nv.%1$d", fr:"⭐ Niv.%1$d", de:"⭐ Lv.%1$d", pt:"⭐ Nv.%1$d", ru:"⭐ Ур.%1$d", vi:"⭐ Cấp %1$d", th:"⭐ Lv.%1$d", in:"⭐ Lv.%1$d" },
stats_xp_detail: { ko:"누적 %1$d XP · 다음 레벨까지 %2$d XP", en:"%1$d XP total · %2$d XP to next level", ja:"るいけい %1$d XP · つぎの レベルまで %2$d XP", zh:"累计 %1$d XP · 距下一级 %2$d XP", es:"%1$d XP en total · %2$d XP al siguiente nivel", fr:"%1$d XP au total · %2$d XP avant le niveau suivant", de:"%1$d XP gesamt · %2$d XP bis zum nächsten Level", pt:"%1$d XP no total · %2$d XP para o próximo nível", ru:"Всего %1$d XP · до следующего уровня %2$d XP", vi:"Tổng %1$d XP · còn %2$d XP lên cấp", th:"รวม %1$d XP · อีก %2$d XP ถึงระดับถัดไป", in:"Total %1$d XP · %2$d XP lagi naik level" },
stats_streak_info: { ko:"현재 %1$d일 연속 · 최고 %2$d일", en:"%1$d-day streak · best %2$d days", ja:"いま %1$d日 れんぞく · さいこう %2$d日", zh:"当前连续 %1$d 天 · 最长 %2$d 天", es:"Racha de %1$d días · mejor %2$d días", fr:"Série de %1$d jours · record %2$d jours", de:"%1$d Tage in Folge · Rekord %2$d Tage", pt:"Sequência de %1$d dias · recorde %2$d dias", ru:"Серия %1$d дней · рекорд %2$d дней", vi:"Chuỗi %1$d ngày · kỷ lục %2$d ngày", th:"ต่อเนื่อง %1$d วัน · สูงสุด %2$d วัน", in:"Beruntun %1$d hari · terbaik %2$d hari" },
stats_none_yet: { ko:"아직 풀어본 문제가 없어요", en:"No questions solved yet", ja:"まだ といた もんだいが ないよ", zh:"还没做过题", es:"Aún no has resuelto preguntas", fr:"Aucune question résolue pour l'instant", de:"Noch keine Aufgaben gelöst", pt:"Nenhuma questão resolvida ainda", ru:"Пока нет решённых задач", vi:"Chưa giải câu nào", th:"ยังไม่ได้ทำโจทย์", in:"Belum ada soal dikerjakan" },
stats_skill_line: { ko:"정답 %1$d / 시도 %2$d  ·  정답률 %3$d%%", en:"%1$d correct / %2$d tries  ·  %3$d%% accuracy", ja:"せいかい %1$d / ちょうせん %2$d  ·  せいかいりつ %3$d%%", zh:"答对 %1$d / 尝试 %2$d  ·  正确率 %3$d%%", es:"%1$d aciertos / %2$d intentos  ·  %3$d%% de acierto", fr:"%1$d bonnes / %2$d essais  ·  %3$d%% de réussite", de:"%1$d richtig / %2$d Versuche  ·  %3$d%% Trefferquote", pt:"%1$d certas / %2$d tentativas  ·  %3$d%% de acerto", ru:"%1$d верно / %2$d попыток  ·  точность %3$d%%", vi:"%1$d đúng / %2$d lần  ·  chính xác %3$d%%", th:"ถูก %1$d / ลอง %2$d  ·  ความแม่นยำ %3$d%%", in:"%1$d benar / %2$d percobaan  ·  akurasi %3$d%%" },
stats_next_level: { ko:"  ·  다음 레벨까지 %1$d문제", en:"  ·  %1$d more to level up", ja:"  ·  つぎの レベルまで %1$d もん", zh:"  ·  距升级还差 %1$d 题", es:"  ·  %1$d más para subir de nivel", fr:"  ·  %1$d de plus pour monter", de:"  ·  noch %1$d bis zum Aufstieg", pt:"  ·  mais %1$d para subir de nível", ru:"  ·  ещё %1$d до уровня", vi:"  ·  còn %1$d câu để lên cấp", th:"  ·  อีก %1$d ข้อจะเลื่อนระดับ", in:"  ·  %1$d lagi untuk naik level" },
stats_max_level: { ko:"  ·  최고 레벨!", en:"  ·  Max level!", ja:"  ·  さいこう レベル!", zh:"  ·  已达最高等级!", es:"  ·  ¡Nivel máximo!", fr:"  ·  Niveau max !", de:"  ·  Höchstlevel!", pt:"  ·  Nível máximo!", ru:"  ·  Максимальный уровень!", vi:"  ·  Cấp tối đa!", th:"  ·  ระดับสูงสุด!", in:"  ·  Level maksimum!" },

};
