/** 유닛 제목 번역 2/3 — 초등 3~6학년 */
module.exports = {

// ---------- 초등 3학년 ----------
"나눗셈 (똑같이 나누기)": { en:"Division (sharing equally)", ja:"わりざん (おなじに わける)", zh:"除法 (平均分)", es:"División (repartir por igual)", fr:"Division (partage égal)", de:"Division (gleich aufteilen)", pt:"Divisão (repartir igualmente)", ru:"Деление (поровну)", vi:"Phép chia (chia đều)", th:"การหาร (แบ่งเท่ากัน)", in:"Pembagian (bagi rata)" },
"끌어서 똑같이 나누기": { en:"Drag to share equally", ja:"ドラッグして おなじに わける", zh:"拖动平均分", es:"Arrastra para repartir igual", fr:"Fais glisser pour partager", de:"Ziehen und gleich aufteilen", pt:"Arraste para repartir igual", ru:"Перетащи и раздели поровну", vi:"Kéo để chia đều", th:"ลากเพื่อแบ่งเท่ากัน", in:"Seret untuk bagi rata" },
"두 자리 × 한 자리": { en:"Two-digit × one-digit", ja:"2けた × 1けた", zh:"两位数 × 一位数", es:"Dos cifras × una cifra", fr:"Deux chiffres × un chiffre", de:"Zweistellig × einstellig", pt:"Dois algarismos × um", ru:"Двузначное × однозначное", vi:"Hai chữ số × một chữ số", th:"สองหลัก × หนึ่งหลัก", in:"Dua angka × satu angka" },
"분수 알아보기": { en:"Understanding fractions", ja:"ぶんすうを しる", zh:"认识分数", es:"Conocer las fracciones", fr:"Découvrir les fractions", de:"Brüche verstehen", pt:"Conhecer frações", ru:"Знакомство с дробями", vi:"Làm quen phân số", th:"รู้จักเศษส่วน", in:"Mengenal pecahan" },
"분수만큼 색칠하기": { en:"Color the fraction", ja:"ぶんすうだけ ぬる", zh:"按分数涂色", es:"Colorea la fracción", fr:"Colorie la fraction", de:"Bruch anmalen", pt:"Pinte a fração", ru:"Закрась дробь", vi:"Tô theo phân số", th:"ระบายสีตามเศษส่วน", in:"Warnai sesuai pecahan" },
"소수 알아보기": { en:"Understanding decimals", ja:"しょうすうを しる", zh:"认识小数", es:"Conocer los decimales", fr:"Découvrir les décimaux", de:"Dezimalzahlen verstehen", pt:"Conhecer decimais", ru:"Знакомство с десятичными", vi:"Làm quen số thập phân", th:"รู้จักทศนิยม", in:"Mengenal desimal" },
"수직선에서 소수 찾기": { en:"Decimals on the number line", ja:"すうちょくせんで しょうすうを さがす", zh:"在数轴上找小数", es:"Decimales en la recta numérica", fr:"Décimaux sur la droite numérique", de:"Dezimalzahlen am Zahlenstrahl", pt:"Decimais na reta numérica", ru:"Десятичные на числовой прямой", vi:"Số thập phân trên trục số", th:"ทศนิยมบนเส้นจำนวน", in:"Desimal di garis bilangan" },
"소수만큼 색칠하기": { en:"Color the decimal", ja:"しょうすうだけ ぬる", zh:"按小数涂色", es:"Colorea el decimal", fr:"Colorie le décimal", de:"Dezimalzahl anmalen", pt:"Pinte o decimal", ru:"Закрась десятичную", vi:"Tô theo số thập phân", th:"ระบายสีตามทศนิยม", in:"Warnai sesuai desimal" },
"직각과 평면도형": { en:"Right angles and plane shapes", ja:"ちょっかくと へいめんずけい", zh:"直角与平面图形", es:"Ángulos rectos y figuras planas", fr:"Angles droits et figures planes", de:"Rechte Winkel und Flächenformen", pt:"Ângulos retos e figuras planas", ru:"Прямые углы и плоские фигуры", vi:"Góc vuông và hình phẳng", th:"มุมฉากและรูปเรขาคณิตระนาบ", in:"Sudut siku dan bangun datar" },
"도형 분류하기": { en:"Classifying shapes", ja:"ずけいを わける", zh:"图形分类", es:"Clasificar figuras", fr:"Classer les figures", de:"Formen einteilen", pt:"Classificar figuras", ru:"Классификация фигур", vi:"Phân loại hình", th:"จำแนกรูปทรง", in:"Mengelompokkan bangun" },
"길이와 시간": { en:"Length and time", ja:"ながさと じかん", zh:"长度与时间", es:"Longitud y tiempo", fr:"Longueur et temps", de:"Länge und Zeit", pt:"Comprimento e tempo", ru:"Длина и время", vi:"Độ dài và thời gian", th:"ความยาวและเวลา", in:"Panjang dan waktu" },
"무게와 들이": { en:"Weight and capacity", ja:"おもさと かさ", zh:"重量与容积", es:"Peso y capacidad", fr:"Masse et contenance", de:"Gewicht und Fassungsvermögen", pt:"Peso e capacidade", ru:"Масса и объём", vi:"Khối lượng và dung tích", th:"น้ำหนักและความจุ", in:"Berat dan kapasitas" },
"이야기 문제 (곱하기·나누기)": { en:"Word problems (× and ÷)", ja:"ぶんしょうだい (かける・わる)", zh:"应用题 (乘·除)", es:"Problemas (× y ÷)", fr:"Problèmes (× et ÷)", de:"Textaufgaben (× und ÷)", pt:"Problemas (× e ÷)", ru:"Задачи (× и ÷)", vi:"Toán đố (nhân · chia)", th:"โจทย์ปัญหา (คูณ·หาร)", in:"Soal cerita (× dan ÷)" },

// ---------- 초등 4학년 ----------
"큰 수": { en:"Large numbers", ja:"おおきい かず", zh:"大数", es:"Números grandes", fr:"Grands nombres", de:"Große Zahlen", pt:"Números grandes", ru:"Большие числа", vi:"Số lớn", th:"จำนวนขนาดใหญ่", in:"Bilangan besar" },
"각도 만들기": { en:"Making angles", ja:"かくどを つくる", zh:"做出角度", es:"Formar ángulos", fr:"Former des angles", de:"Winkel bilden", pt:"Formar ângulos", ru:"Построение углов", vi:"Tạo góc", th:"สร้างมุม", in:"Membuat sudut" },
"각도 재기": { en:"Measuring angles", ja:"かくどを はかる", zh:"测量角度", es:"Medir ángulos", fr:"Mesurer les angles", de:"Winkel messen", pt:"Medir ângulos", ru:"Измерение углов", vi:"Đo góc", th:"วัดมุม", in:"Mengukur sudut" },
"세 자리 × 두 자리": { en:"Three-digit × two-digit", ja:"3けた × 2けた", zh:"三位数 × 两位数", es:"Tres cifras × dos cifras", fr:"Trois chiffres × deux chiffres", de:"Dreistellig × zweistellig", pt:"Três algarismos × dois", ru:"Трёхзначное × двузначное", vi:"Ba chữ số × hai chữ số", th:"สามหลัก × สองหลัก", in:"Tiga angka × dua angka" },
"나눗셈 (몫과 나머지)": { en:"Division (quotient and remainder)", ja:"わりざん (しょうと あまり)", zh:"除法 (商与余数)", es:"División (cociente y resto)", fr:"Division (quotient et reste)", de:"Division (Quotient und Rest)", pt:"Divisão (quociente e resto)", ru:"Деление (частное и остаток)", vi:"Phép chia (thương và dư)", th:"การหาร (ผลหารและเศษ)", in:"Pembagian (hasil dan sisa)" },
"분수의 덧셈과 뺄셈": { en:"Adding and subtracting fractions", ja:"ぶんすうの たしざん・ひきざん", zh:"分数的加减", es:"Suma y resta de fracciones", fr:"Addition et soustraction de fractions", de:"Brüche addieren und subtrahieren", pt:"Soma e subtração de frações", ru:"Сложение и вычитание дробей", vi:"Cộng trừ phân số", th:"บวกลบเศษส่วน", in:"Penjumlahan dan pengurangan pecahan" },
"소수의 덧셈과 뺄셈": { en:"Adding and subtracting decimals", ja:"しょうすうの たしざん・ひきざん", zh:"小数的加减", es:"Suma y resta de decimales", fr:"Addition et soustraction de décimaux", de:"Dezimalzahlen addieren und subtrahieren", pt:"Soma e subtração de decimais", ru:"Сложение и вычитание десятичных", vi:"Cộng trừ số thập phân", th:"บวกลบทศนิยม", in:"Penjumlahan dan pengurangan desimal" },
"그래프 세우기 (큰 수)": { en:"Build a graph (large numbers)", ja:"グラフを つくる (おおきい かず)", zh:"制作图表 (大数)", es:"Construye un gráfico (números grandes)", fr:"Construis un graphique (grands nombres)", de:"Diagramm bauen (große Zahlen)", pt:"Monte um gráfico (números grandes)", ru:"Построй график (большие числа)", vi:"Dựng biểu đồ (số lớn)", th:"สร้างกราฟ (จำนวนใหญ่)", in:"Buat grafik (bilangan besar)" },
"막대그래프 읽기": { en:"Reading bar graphs", ja:"ぼうグラフを よむ", zh:"读条形图", es:"Leer gráficos de barras", fr:"Lire des diagrammes en barres", de:"Balkendiagramme lesen", pt:"Ler gráficos de barras", ru:"Чтение столбчатых диаграмм", vi:"Đọc biểu đồ cột", th:"อ่านกราฟแท่ง", in:"Membaca grafik batang" },
"이야기 문제 (두 단계)": { en:"Two-step word problems", ja:"ぶんしょうだい (2だんかい)", zh:"两步应用题", es:"Problemas de dos pasos", fr:"Problèmes à deux étapes", de:"Zweischrittige Textaufgaben", pt:"Problemas de duas etapas", ru:"Задачи в два действия", vi:"Toán đố hai bước", th:"โจทย์ปัญหาสองขั้นตอน", in:"Soal cerita dua langkah" },

// ---------- 초등 5학년 ----------
"자연수의 혼합 계산": { en:"Mixed operations", ja:"しぜんすうの こんごう けいさん", zh:"四则混合运算", es:"Operaciones combinadas", fr:"Calculs mixtes", de:"Gemischte Rechnungen", pt:"Operações combinadas", ru:"Смешанные вычисления", vi:"Tính hỗn hợp", th:"การคำนวณผสม", in:"Operasi campuran" },
"약수와 배수": { en:"Factors and multiples", ja:"やくすうと ばいすう", zh:"因数与倍数", es:"Divisores y múltiplos", fr:"Diviseurs et multiples", de:"Teiler und Vielfache", pt:"Divisores e múltiplos", ru:"Делители и кратные", vi:"Ước và bội", th:"ตัวประกอบและพหุคูณ", in:"Faktor dan kelipatan" },
"약분과 통분": { en:"Reducing and common denominators", ja:"やくぶんと つうぶん", zh:"约分与通分", es:"Simplificar y común denominador", fr:"Simplifier et réduire au même dénominateur", de:"Kürzen und gleichnamig machen", pt:"Simplificar e denominador comum", ru:"Сокращение и общий знаменатель", vi:"Rút gọn và quy đồng", th:"การลดรูปและทำส่วนร่วม", in:"Menyederhanakan dan menyamakan penyebut" },
"분수의 곱셈": { en:"Multiplying fractions", ja:"ぶんすうの かけざん", zh:"分数乘法", es:"Multiplicación de fracciones", fr:"Multiplication de fractions", de:"Brüche multiplizieren", pt:"Multiplicação de frações", ru:"Умножение дробей", vi:"Nhân phân số", th:"การคูณเศษส่วน", in:"Perkalian pecahan" },
"다각형의 넓이": { en:"Area of polygons", ja:"たかっけいの めんせき", zh:"多边形的面积", es:"Área de polígonos", fr:"Aire des polygones", de:"Flächeninhalt von Vielecken", pt:"Área de polígonos", ru:"Площадь многоугольников", vi:"Diện tích đa giác", th:"พื้นที่รูปหลายเหลี่ยม", in:"Luas poligon" },
"평균 구하기": { en:"Finding the average", ja:"へいきんを もとめる", zh:"求平均数", es:"Calcular la media", fr:"Calculer la moyenne", de:"Durchschnitt berechnen", pt:"Calcular a média", ru:"Нахождение среднего", vi:"Tìm số trung bình", th:"หาค่าเฉลี่ย", in:"Mencari rata-rata" },
"이야기 문제 (평균·비율)": { en:"Word problems (average, ratio)", ja:"ぶんしょうだい (へいきん・わりあい)", zh:"应用题 (平均·比率)", es:"Problemas (media y proporción)", fr:"Problèmes (moyenne, proportion)", de:"Textaufgaben (Durchschnitt, Anteil)", pt:"Problemas (média e proporção)", ru:"Задачи (среднее, доля)", vi:"Toán đố (trung bình · tỉ lệ)", th:"โจทย์ปัญหา (ค่าเฉลี่ย·อัตราส่วน)", in:"Soal cerita (rata-rata, rasio)" },

// ---------- 초등 6학년 ----------
"분수의 나눗셈": { en:"Dividing fractions", ja:"ぶんすうの わりざん", zh:"分数除法", es:"División de fracciones", fr:"Division de fractions", de:"Brüche dividieren", pt:"Divisão de frações", ru:"Деление дробей", vi:"Chia phân số", th:"การหารเศษส่วน", in:"Pembagian pecahan" },
"소수의 나눗셈": { en:"Dividing decimals", ja:"しょうすうの わりざん", zh:"小数除法", es:"División de decimales", fr:"Division de décimaux", de:"Dezimalzahlen dividieren", pt:"Divisão de decimais", ru:"Деление десятичных", vi:"Chia số thập phân", th:"การหารทศนิยม", in:"Pembagian desimal" },
"비와 비율": { en:"Ratio and rate", ja:"ひと わりあい", zh:"比与比率", es:"Razón y proporción", fr:"Rapport et proportion", de:"Verhältnis und Anteil", pt:"Razão e proporção", ru:"Отношение и доля", vi:"Tỉ số và tỉ lệ", th:"อัตราส่วนและอัตรา", in:"Rasio dan perbandingan" },
"백분율": { en:"Percentages", ja:"ひゃくぶんりつ", zh:"百分率", es:"Porcentajes", fr:"Pourcentages", de:"Prozent", pt:"Porcentagem", ru:"Проценты", vi:"Phần trăm", th:"ร้อยละ", in:"Persentase" },
"원의 넓이와 둘레": { en:"Area and circumference of a circle", ja:"えんの めんせきと まわり", zh:"圆的面积与周长", es:"Área y perímetro del círculo", fr:"Aire et périmètre du cercle", de:"Kreisfläche und Umfang", pt:"Área e perímetro do círculo", ru:"Площадь и длина окружности", vi:"Diện tích và chu vi hình tròn", th:"พื้นที่และเส้นรอบวงกลม", in:"Luas dan keliling lingkaran" },
"직육면체의 부피와 겉넓이": { en:"Volume and surface area of a cuboid", ja:"ちょくほうたいの たいせきと ひょうめんせき", zh:"长方体的体积与表面积", es:"Volumen y área del prisma", fr:"Volume et aire du pavé droit", de:"Volumen und Oberfläche des Quaders", pt:"Volume e área do paralelepípedo", ru:"Объём и площадь поверхности параллелепипеда", vi:"Thể tích và diện tích hình hộp", th:"ปริมาตรและพื้นที่ผิวทรงสี่เหลี่ยม", in:"Volume dan luas permukaan balok" },
"여러 가지 그래프": { en:"Various graphs", ja:"いろいろな グラフ", zh:"各种图表", es:"Distintos gráficos", fr:"Divers graphiques", de:"Verschiedene Diagramme", pt:"Vários gráficos", ru:"Разные диаграммы", vi:"Các loại biểu đồ", th:"กราฟหลากหลายแบบ", in:"Berbagai grafik" },
"이야기 문제 (비율·속력)": { en:"Word problems (rate and speed)", ja:"ぶんしょうだい (わりあい・そくど)", zh:"应用题 (比率·速度)", es:"Problemas (proporción y velocidad)", fr:"Problèmes (proportion et vitesse)", de:"Textaufgaben (Anteil, Geschwindigkeit)", pt:"Problemas (proporção e velocidade)", ru:"Задачи (доля и скорость)", vi:"Toán đố (tỉ lệ · vận tốc)", th:"โจทย์ปัญหา (อัตราส่วน·ความเร็ว)", in:"Soal cerita (rasio dan kecepatan)" },

};
