/** 유닛 제목 번역 3/3 — 중·고등학교 */
module.exports = {

// ---------- 중학교 1학년 ----------
"소인수분해": { en:"Prime factorization", ja:"そいんすうぶんかい", zh:"质因数分解", es:"Factorización en primos", fr:"Décomposition en facteurs premiers", de:"Primfaktorzerlegung", pt:"Fatoração em primos", ru:"Разложение на простые множители", vi:"Phân tích thừa số nguyên tố", th:"การแยกตัวประกอบเฉพาะ", in:"Faktorisasi prima" },
"정수와 유리수의 계산": { en:"Integers and rational numbers", ja:"せいすうと ゆうりすうの けいさん", zh:"整数与有理数运算", es:"Enteros y racionales", fr:"Entiers et rationnels", de:"Ganze und rationale Zahlen", pt:"Inteiros e racionais", ru:"Целые и рациональные числа", vi:"Số nguyên và số hữu tỉ", th:"จำนวนเต็มและจำนวนตรรกยะ", in:"Bilangan bulat dan rasional" },
"문자와 식": { en:"Letters and expressions", ja:"もじと しき", zh:"字母与式", es:"Letras y expresiones", fr:"Lettres et expressions", de:"Variablen und Terme", pt:"Letras e expressões", ru:"Буквы и выражения", vi:"Chữ và biểu thức", th:"ตัวอักษรและนิพจน์", in:"Huruf dan bentuk aljabar" },
"일차방정식": { en:"Linear equations", ja:"いちじほうていしき", zh:"一元一次方程", es:"Ecuaciones lineales", fr:"Équations du premier degré", de:"Lineare Gleichungen", pt:"Equações do 1º grau", ru:"Линейные уравнения", vi:"Phương trình bậc nhất", th:"สมการเชิงเส้น", in:"Persamaan linear" },
"저울로 방정식 풀기": { en:"Solving equations with a balance", ja:"てんびんで ほうていしきを とく", zh:"用天平解方程", es:"Resolver ecuaciones con balanza", fr:"Résoudre avec une balance", de:"Gleichungen mit der Waage lösen", pt:"Resolver equações com balança", ru:"Решаем уравнения на весах", vi:"Giải phương trình bằng cân", th:"แก้สมการด้วยตาชั่ง", in:"Menyelesaikan persamaan dengan timbangan" },
"수직선에서 정수 찾기": { en:"Integers on the number line", ja:"すうちょくせんで せいすうを さがす", zh:"在数轴上找整数", es:"Enteros en la recta numérica", fr:"Entiers sur la droite numérique", de:"Ganze Zahlen am Zahlenstrahl", pt:"Inteiros na reta numérica", ru:"Целые на числовой прямой", vi:"Số nguyên trên trục số", th:"จำนวนเต็มบนเส้นจำนวน", in:"Bilangan bulat di garis bilangan" },
"정비례와 반비례": { en:"Direct and inverse proportion", ja:"せいひれいと はんぴれい", zh:"正比例与反比例", es:"Proporción directa e inversa", fr:"Proportionnalité directe et inverse", de:"Direkte und umgekehrte Proportionalität", pt:"Proporção direta e inversa", ru:"Прямая и обратная пропорция", vi:"Tỉ lệ thuận và nghịch", th:"การแปรผันตรงและผกผัน", in:"Perbandingan lurus dan berbalik" },
"평면도형의 성질": { en:"Properties of plane figures", ja:"へいめんずけいの せいしつ", zh:"平面图形的性质", es:"Propiedades de figuras planas", fr:"Propriétés des figures planes", de:"Eigenschaften ebener Figuren", pt:"Propriedades de figuras planas", ru:"Свойства плоских фигур", vi:"Tính chất hình phẳng", th:"สมบัติของรูปเรขาคณิตระนาบ", in:"Sifat bangun datar" },
"입체도형의 겉넓이와 부피": { en:"Surface area and volume of solids", ja:"りったいずけいの ひょうめんせきと たいせき", zh:"立体图形的表面积与体积", es:"Área y volumen de sólidos", fr:"Aire et volume des solides", de:"Oberfläche und Volumen von Körpern", pt:"Área e volume de sólidos", ru:"Площадь поверхности и объём тел", vi:"Diện tích và thể tích khối", th:"พื้นที่ผิวและปริมาตรทรงตัน", in:"Luas permukaan dan volume bangun ruang" },
"자료의 정리와 해석": { en:"Organizing and interpreting data", ja:"データの せいりと かいしゃく", zh:"数据的整理与解释", es:"Organizar e interpretar datos", fr:"Organiser et interpréter des données", de:"Daten ordnen und deuten", pt:"Organizar e interpretar dados", ru:"Обработка и анализ данных", vi:"Sắp xếp và phân tích dữ liệu", th:"การจัดระเบียบและตีความข้อมูล", in:"Mengolah dan menafsirkan data" },
"방정식 문장제": { en:"Equation word problems", ja:"ほうていしきの ぶんしょうだい", zh:"方程应用题", es:"Problemas con ecuaciones", fr:"Problèmes avec équations", de:"Gleichungs-Textaufgaben", pt:"Problemas com equações", ru:"Текстовые задачи на уравнения", vi:"Toán đố phương trình", th:"โจทย์ปัญหาสมการ", in:"Soal cerita persamaan" },

// ---------- 중학교 2학년 ----------
"지수법칙": { en:"Laws of exponents", ja:"しすうほうそく", zh:"指数法则", es:"Leyes de los exponentes", fr:"Lois des exposants", de:"Potenzgesetze", pt:"Propriedades das potências", ru:"Свойства степеней", vi:"Quy tắc lũy thừa", th:"กฎเลขยกกำลัง", in:"Sifat eksponen" },
"일차부등식": { en:"Linear inequalities", ja:"いちじふとうしき", zh:"一元一次不等式", es:"Inecuaciones lineales", fr:"Inéquations du premier degré", de:"Lineare Ungleichungen", pt:"Inequações do 1º grau", ru:"Линейные неравенства", vi:"Bất phương trình bậc nhất", th:"อสมการเชิงเส้น", in:"Pertidaksamaan linear" },
"연립방정식": { en:"Systems of equations", ja:"れんりつほうていしき", zh:"方程组", es:"Sistemas de ecuaciones", fr:"Systèmes d'équations", de:"Gleichungssysteme", pt:"Sistemas de equações", ru:"Системы уравнений", vi:"Hệ phương trình", th:"ระบบสมการ", in:"Sistem persamaan" },
"일차함수와 그래프": { en:"Linear functions and graphs", ja:"いちじかんすうと グラフ", zh:"一次函数与图象", es:"Funciones lineales y gráficas", fr:"Fonctions affines et graphiques", de:"Lineare Funktionen und Graphen", pt:"Funções lineares e gráficos", ru:"Линейные функции и графики", vi:"Hàm số bậc nhất và đồ thị", th:"ฟังก์ชันเชิงเส้นและกราฟ", in:"Fungsi linear dan grafik" },
"피타고라스 정리": { en:"Pythagorean theorem", ja:"ピタゴラスの ていり", zh:"勾股定理", es:"Teorema de Pitágoras", fr:"Théorème de Pythagore", de:"Satz des Pythagoras", pt:"Teorema de Pitágoras", ru:"Теорема Пифагора", vi:"Định lý Pythagoras", th:"ทฤษฎีบทพีทาโกรัส", in:"Teorema Pythagoras" },
"도형의 닮음": { en:"Similar figures", ja:"ずけいの そうじ", zh:"图形的相似", es:"Figuras semejantes", fr:"Figures semblables", de:"Ähnliche Figuren", pt:"Figuras semelhantes", ru:"Подобие фигур", vi:"Hình đồng dạng", th:"รูปคล้าย", in:"Kesebangunan bangun" },
"확률": { en:"Probability", ja:"かくりつ", zh:"概率", es:"Probabilidad", fr:"Probabilité", de:"Wahrscheinlichkeit", pt:"Probabilidade", ru:"Вероятность", vi:"Xác suất", th:"ความน่าจะเป็น", in:"Peluang" },

// ---------- 중학교 3학년 ----------
"제곱근과 실수": { en:"Square roots and real numbers", ja:"へいほうこんと じっすう", zh:"平方根与实数", es:"Raíces cuadradas y reales", fr:"Racines carrées et réels", de:"Quadratwurzeln und reelle Zahlen", pt:"Raízes quadradas e reais", ru:"Квадратные корни и вещественные числа", vi:"Căn bậc hai và số thực", th:"รากที่สองและจำนวนจริง", in:"Akar kuadrat dan bilangan real" },
"인수분해": { en:"Factorization", ja:"いんすうぶんかい", zh:"因式分解", es:"Factorización", fr:"Factorisation", de:"Faktorisierung", pt:"Fatoração", ru:"Разложение на множители", vi:"Phân tích thành nhân tử", th:"การแยกตัวประกอบ", in:"Pemfaktoran" },
"이차방정식": { en:"Quadratic equations", ja:"にじほうていしき", zh:"一元二次方程", es:"Ecuaciones cuadráticas", fr:"Équations du second degré", de:"Quadratische Gleichungen", pt:"Equações do 2º grau", ru:"Квадратные уравнения", vi:"Phương trình bậc hai", th:"สมการกำลังสอง", in:"Persamaan kuadrat" },
"이차함수": { en:"Quadratic functions", ja:"にじかんすう", zh:"二次函数", es:"Funciones cuadráticas", fr:"Fonctions du second degré", de:"Quadratische Funktionen", pt:"Funções quadráticas", ru:"Квадратичные функции", vi:"Hàm số bậc hai", th:"ฟังก์ชันกำลังสอง", in:"Fungsi kuadrat" },
"삼각비": { en:"Trigonometric ratios", ja:"さんかくひ", zh:"三角比", es:"Razones trigonométricas", fr:"Rapports trigonométriques", de:"Trigonometrische Verhältnisse", pt:"Razões trigonométricas", ru:"Тригонометрические отношения", vi:"Tỉ số lượng giác", th:"อัตราส่วนตรีโกณมิติ", in:"Perbandingan trigonometri" },
"원의 성질": { en:"Properties of circles", ja:"えんの せいしつ", zh:"圆的性质", es:"Propiedades del círculo", fr:"Propriétés du cercle", de:"Eigenschaften des Kreises", pt:"Propriedades do círculo", ru:"Свойства окружности", vi:"Tính chất đường tròn", th:"สมบัติของวงกลม", in:"Sifat lingkaran" },
"통계 (대푯값)": { en:"Statistics (measures of center)", ja:"とうけい (だいひょうち)", zh:"统计 (代表值)", es:"Estadística (medidas de centro)", fr:"Statistiques (valeurs centrales)", de:"Statistik (Mittelwerte)", pt:"Estatística (medidas de centro)", ru:"Статистика (средние значения)", vi:"Thống kê (số đại diện)", th:"สถิติ (ค่ากลาง)", in:"Statistika (ukuran pemusatan)" },

// ---------- 고등학교 ----------
"다항식과 나머지정리": { en:"Polynomials and remainder theorem", ja:"たこうしきと じょうよていり", zh:"多项式与余数定理", es:"Polinomios y teorema del resto", fr:"Polynômes et théorème du reste", de:"Polynome und Restsatz", pt:"Polinômios e teorema do resto", ru:"Многочлены и теорема об остатке", vi:"Đa thức và định lý phần dư", th:"พหุนามและทฤษฎีบทเศษเหลือ", in:"Polinomial dan teorema sisa" },
"이차방정식과 판별식": { en:"Quadratics and the discriminant", ja:"にじほうていしきと はんべつしき", zh:"二次方程与判别式", es:"Cuadráticas y discriminante", fr:"Équations du second degré et discriminant", de:"Quadratische Gleichungen und Diskriminante", pt:"Quadráticas e discriminante", ru:"Квадратные уравнения и дискриминант", vi:"Phương trình bậc hai và biệt thức", th:"สมการกำลังสองและดิสคริมิแนนต์", in:"Kuadrat dan diskriminan" },
"순열과 조합": { en:"Permutations and combinations", ja:"じゅんれつと くみあわせ", zh:"排列与组合", es:"Permutaciones y combinaciones", fr:"Permutations et combinaisons", de:"Permutationen und Kombinationen", pt:"Permutações e combinações", ru:"Перестановки и сочетания", vi:"Hoán vị và tổ hợp", th:"การเรียงสับเปลี่ยนและการจัดหมู่", in:"Permutasi dan kombinasi" },
"도형의 방정식": { en:"Equations of figures", ja:"ずけいの ほうていしき", zh:"图形的方程", es:"Ecuaciones de figuras", fr:"Équations de figures", de:"Gleichungen von Figuren", pt:"Equações de figuras", ru:"Уравнения фигур", vi:"Phương trình hình học", th:"สมการของรูปเรขาคณิต", in:"Persamaan bangun" },
"집합과 명제": { en:"Sets and propositions", ja:"しゅうごうと めいだい", zh:"集合与命题", es:"Conjuntos y proposiciones", fr:"Ensembles et propositions", de:"Mengen und Aussagen", pt:"Conjuntos e proposições", ru:"Множества и высказывания", vi:"Tập hợp và mệnh đề", th:"เซตและประพจน์", in:"Himpunan dan proposisi" },
"지수와 로그": { en:"Exponents and logarithms", ja:"しすうと たいすう", zh:"指数与对数", es:"Exponentes y logaritmos", fr:"Exposants et logarithmes", de:"Exponenten und Logarithmen", pt:"Expoentes e logaritmos", ru:"Степени и логарифмы", vi:"Lũy thừa và logarit", th:"เลขยกกำลังและลอการิทึม", in:"Eksponen dan logaritma" },
"삼각함수": { en:"Trigonometric functions", ja:"さんかくかんすう", zh:"三角函数", es:"Funciones trigonométricas", fr:"Fonctions trigonométriques", de:"Trigonometrische Funktionen", pt:"Funções trigonométricas", ru:"Тригонометрические функции", vi:"Hàm số lượng giác", th:"ฟังก์ชันตรีโกณมิติ", in:"Fungsi trigonometri" },
"수열": { en:"Sequences", ja:"すうれつ", zh:"数列", es:"Sucesiones", fr:"Suites", de:"Folgen", pt:"Sequências", ru:"Последовательности", vi:"Dãy số", th:"ลำดับ", in:"Barisan" },
"함수의 극한": { en:"Limits of functions", ja:"かんすうの きょくげん", zh:"函数的极限", es:"Límites de funciones", fr:"Limites de fonctions", de:"Grenzwerte von Funktionen", pt:"Limites de funções", ru:"Пределы функций", vi:"Giới hạn hàm số", th:"ลิมิตของฟังก์ชัน", in:"Limit fungsi" },
"미분": { en:"Differentiation", ja:"びぶん", zh:"微分", es:"Derivación", fr:"Dérivation", de:"Differentiation", pt:"Derivação", ru:"Дифференцирование", vi:"Đạo hàm", th:"อนุพันธ์", in:"Turunan" },
"적분": { en:"Integration", ja:"せきぶん", zh:"积分", es:"Integración", fr:"Intégration", de:"Integration", pt:"Integração", ru:"Интегрирование", vi:"Tích phân", th:"ปริพันธ์", in:"Integral" },
"수열의 극한": { en:"Limits of sequences", ja:"すうれつの きょくげん", zh:"数列的极限", es:"Límites de sucesiones", fr:"Limites de suites", de:"Grenzwerte von Folgen", pt:"Limites de sequências", ru:"Пределы последовательностей", vi:"Giới hạn dãy số", th:"ลิมิตของลำดับ", in:"Limit barisan" },
"여러 가지 함수의 미분": { en:"Derivatives of various functions", ja:"いろいろな かんすうの びぶん", zh:"各种函数的导数", es:"Derivadas de varias funciones", fr:"Dérivées de diverses fonctions", de:"Ableitungen verschiedener Funktionen", pt:"Derivadas de várias funções", ru:"Производные различных функций", vi:"Đạo hàm các hàm số", th:"อนุพันธ์ของฟังก์ชันต่าง ๆ", in:"Turunan berbagai fungsi" },
"정적분과 넓이": { en:"Definite integrals and area", ja:"ていせきぶんと めんせき", zh:"定积分与面积", es:"Integrales definidas y área", fr:"Intégrales définies et aire", de:"Bestimmte Integrale und Fläche", pt:"Integrais definidas e área", ru:"Определённые интегралы и площадь", vi:"Tích phân xác định và diện tích", th:"ปริพันธ์จำกัดเขตและพื้นที่", in:"Integral tentu dan luas" },
"확률과 통계": { en:"Probability and statistics", ja:"かくりつと とうけい", zh:"概率与统计", es:"Probabilidad y estadística", fr:"Probabilités et statistiques", de:"Wahrscheinlichkeit und Statistik", pt:"Probabilidade e estatística", ru:"Вероятность и статистика", vi:"Xác suất và thống kê", th:"ความน่าจะเป็นและสถิติ", in:"Peluang dan statistika" },
"공간도형과 벡터": { en:"Solid geometry and vectors", ja:"くうかんずけいと ベクトル", zh:"空间图形与向量", es:"Geometría del espacio y vectores", fr:"Géométrie dans l'espace et vecteurs", de:"Raumgeometrie und Vektoren", pt:"Geometria espacial e vetores", ru:"Пространственная геометрия и векторы", vi:"Hình không gian và vectơ", th:"เรขาคณิตสามมิติและเวกเตอร์", in:"Geometri ruang dan vektor" },
"이차곡선": { en:"Conic sections", ja:"にじきょくせん", zh:"二次曲线", es:"Cónicas", fr:"Coniques", de:"Kegelschnitte", pt:"Cônicas", ru:"Кривые второго порядка", vi:"Đường conic", th:"ภาคตัดกรวย", in:"Irisan kerucut" },

};
